"""
BLS Sector Patterns - Economic sector definitions and keywords
"""
from glue_jobs.utils.rdf_utils import BLS_ENRICHMENT

BLS_SECTOR_PATTERNS = {
    'food_sector': {
        'description': 'Food production, distribution, and consumption chain',
        'sector_uri': BLS_ENRICHMENT.FoodSector,
        'keywords': {
            'cpi': [
                # Main food categories
                'Food',
                'Food at home',
                'Food away from home',
                # Cereals and bakery
                'Cereals and bakery products',
                'Cereals and cereal products',
                'Flour and prepared flour mixes',
                'Breakfast cereal',
                'Rice, pasta, cornmeal',
                'Rice',
                'Bakery products',
                'Bread',
                'White bread',
                'Bread other than white',
                'Fresh biscuits, rolls, muffins',
                'Cakes, cupcakes, and cookies',
                'Cookies',
                'Fresh cakes and cupcakes',
                'Other bakery products',
                'Fresh sweetrolls, coffeecakes, doughnuts',
                'Crackers, bread, and cracker products',
                'Frozen and refrigerated bakery products, pies, tarts, turnovers',
                # Meats, poultry, fish, and eggs
                'Meats, poultry, fish, and eggs',
                'Meats, poultry, and fish',
                'Meats',
                'Beef and veal',
                'Uncooked ground beef',
                'Uncooked beef roasts',
                'Uncooked beef steaks',
                'Uncooked other beef and veal',
                'Pork',
                'Bacon, breakfast sausage, and related products',
                'Bacon and related products',
                'Breakfast sausage and related products',
                'Ham',
                'Ham, excluding canned',
                'Pork chops',
                'Other pork including roasts, steaks, and ribs',
                'Other meats',
                'Frankfurters',
                'Lunchmeats',
                'Poultry',
                'Chicken',
                'Fresh whole chicken',
                'Fresh and frozen chicken parts',
                'Other uncooked poultry including turkey',
                'Fish and seafood',
                'Fresh fish and seafood',
                'Processed fish and seafood',
                'Shelf stable fish and seafood',
                'Frozen fish and seafood',
                'Eggs',
                # Dairy
                'Dairy and related products',
                'Milk',
                'Fresh whole milk',
                'Fresh milk other than whole',
                'Cheese and related products',
                'Ice cream and related products',
                'Other dairy and related products',
                # Fruits and vegetables
                'Fruits and vegetables',
                'Fresh fruits and vegetables',
                'Fresh fruits',
                'Apples',
                'Bananas',
                'Citrus fruits',
                'Oranges, including tangerines',
                'Other fresh fruits',
                'Fresh vegetables',
                'Potatoes',
                'Lettuce',
                'Tomatoes',
                'Other fresh vegetables',
                'Processed fruits and vegetables',
                'Canned fruits and vegetables',
                'Canned fruits',
                'Canned vegetables',
                'Frozen fruits and vegetables',
                'Frozen vegetables',
                'Other processed fruits and vegetables including dried',
                'Dried beans, peas, and lentils',
                # Beverages
                'Nonalcoholic beverages and beverage materials',
                'Juices and nonalcoholic drinks',
                'Carbonated drinks',
                'Frozen noncarbonated juices and drinks',
                'Nonfrozen noncarbonated juices and drinks',
                'Beverage materials including coffee and tea',
                'Coffee',
                'Roasted coffee',
                'Instant coffee',
                'Other beverage materials including tea',
                # Other food at home
                'Other food at home',
                'Sugar and sweets',
                'Sugar and sugar substitutes',
                'Candy and chewing gum',
                'Other sweets',
                'Fats and oils',
                'Butter and margarine',
                'Butter',
                'Margarine',
                'Salad dressing',
                'Other fats and oils including peanut butter',
                'Peanut butter',
                'Other foods',
                'Soups',
                'Frozen and freeze dried prepared foods',
                'Snacks',
                'Spices, seasonings, condiments, sauces',
                'Salt and other seasonings and spices',
                'Olives, pickles, relishes',
                'Sauces and gravies',
                'Other condiments',
                'Baby food and formula',
                'Other miscellaneous foods',
                'Prepared salads',
                # Food away from home
                'Full service meals and snacks',
                'Limited service meals and snacks',
                'Food at employee sites and schools',
                'Food at elementary and secondary schools',
                'Food from vending machines and mobile vendors',
                'Other food away from home',
                # Alcoholic beverages
                'Alcoholic beverages',
                'Alcoholic beverages at home',
                'Beer, ale, and other malt beverages at home',
                'Distilled spirits at home',
                'Whiskey at home',
                'Distilled spirits, excluding whiskey, at home',
                'Wine at home',
                'Alcoholic beverages away from home',
                'Beer, ale, and other malt beverages away from home',
                'Wine away from home',
                'Distilled spirits away from home',
                # Aggregate
                'Food and beverages',
                'Domestically produced farm food',
            ],
            'ppi': ['Food', 'Manufacturing', 'Foodstuffs', 'Feeds', 'Finished Consumer Foods'],
            'eci': ['Food services', 'Accommodation and food', 'Food service'],
            'jolts': ['Food services', 'Accommodation and food services', 'Restaurants',
                      'Drinking places', 'Food service'],
            'empsit': [
                # From Table B-1
                'Food manufacturing',
                'Food and beverage retailers',
                'Food services and drinking places',
                'Accommodation and food services',
                # Beverage
                'Beverage, tobacco, and leather',
            ],
            'ximpim': [
                'Food',
                'Foodstuffs',
                'Beverages',
                'Agricultural products',
                'Food and live animals',
                'Meat and meat preparations',
                'Dairy products',
                'Fish and seafood',
                'Cereals and cereal preparations',
                'Vegetables and fruit',
                'Sugar and confectionery',
                'Coffee, tea, cocoa, spices',
                'Animal feed',
            ],
        },
        'relationship': BLS_ENRICHMENT.foodSectorCorrelation
    },

    'energy_sector': {
        'description': 'Energy production, distribution, and consumption',
        'sector_uri': BLS_ENRICHMENT.EnergySector,
        'keywords': {
            'cpi': [
                'Energy',
                'Energy commodities',
                'Energy services',
                # Fuel
                'Gasoline (all types)',
                'Gasoline, unleaded regular',
                'Gasoline, unleaded midgrade',
                'Gasoline, unleaded premium',
                'Fuel oil',
                'Fuel oil and other fuels',
                'Propane, kerosene, and firewood',
                'Motor fuel',
                'Other motor fuels',
                'Motor oil, coolant, and fluids',
                # Utilities
                'Electricity',
                'Utility (piped) gas service',
                'Fuels and utilities',
                'Household energy',
            ],
            'ppi': ['Energy', 'Goods', 'Materials', 'Fuel', 'Petroleum'],
            'eci': ['Utilities', 'Mining', 'Oil and gas'],
            'jolts': ['Mining', 'Oil and gas extraction', 'Utilities', 'Electric power',
                      'Natural gas', 'Coal mining'],
            'empsit': [
                # From Table B-1
                'Mining and logging',
                'Oil and gas extraction',
                'Coal mining',
                'Mining, quarrying, and oil and gas extraction',
                'Mining (except oil and gas)',
                'Metal ore mining',
                'Nonmetallic mineral mining',
                'Support activities for mining',
                'Utilities',
                'Petroleum and coal products manufacturing',
                'Gasoline stations and fuel dealers',
                'Pipeline transportation',
            ],
            'ximpim': [
                'Fuel',
                'Petroleum',
                'Crude oil',
                'Refined petroleum products',
                'Natural gas',
                'Coal',
                'Energy',
                'Mineral fuels',
                'Petroleum oils',
                'Gas oils',
                'Fuel oils',
                'Liquefied propane and butane',
                'Petroleum gases',
            ],
        },
        'relationship': BLS_ENRICHMENT.energySectorCorrelation
    },

    'housing_sector': {
        'description': 'Housing, construction, and shelter',
        'sector_uri': BLS_ENRICHMENT.HousingSector,
        'keywords': {
            'cpi': [
                'Housing',
                'Shelter',
                # Rent
                'Rent of shelter',
                'Rent of primary residence',
                'Owners\' equivalent rent of residences',
                'Owners\' equivalent rent of primary residence',
                # Lodging
                'Lodging away from home',
                'Housing at school, excluding board',
                'Other lodging away from home including hotels and motels',
                # Insurance and utilities
                'Tenants\' and household insurance',
                'Water and sewer and trash collection services',
                'Water and sewerage maintenance',
                'Garbage and trash collection',
                # Household operations
                'Household operations',
                'Domestic services',
                'Gardening and lawncare services',
                'Moving, storage, freight expense',
                'Repair of household items',
                # Furnishings
                'Household furnishings and supplies',
                'Household furnishings and operations',
                'Window and floor coverings and other linens',
                'Floor coverings',
                'Window coverings',
                'Other linens',
                'Furniture and bedding',
                'Bedroom furniture',
                'Living room, kitchen, and dining room furniture',
                'Other furniture',
                'Appliances',
                'Major appliances',
                'Laundry equipment',
                'Other appliances',
                'Other household equipment and furnishings',
                'Clocks, lamps, and decorator items',
                'Indoor plants and flowers',
                'Dishes and flatware',
                'Nonelectric cookware and tableware',
                'Tools, hardware, outdoor equipment and supplies',
                'Tools, hardware and supplies',
                'Outdoor equipment and supplies',
                'Housekeeping supplies',
                'Household cleaning products',
                'Household paper products',
                'Miscellaneous household products',
            ],
            'ppi': ['Construction', 'Building', 'Materials', 'Residential'],
            'eci': ['Construction', 'Real estate', 'Rental', 'Leasing'],
            'jolts': ['Construction', 'Building construction', 'Heavy construction',
                      'Specialty trade contractors', 'Residential construction'],
            'empsit': [
                'Construction',
                'Construction of buildings',
                'Residential building construction',
                'Nonresidential building construction',
                'Heavy and civil engineering construction',
                'Specialty trade contractors',
                'Residential specialty trade contractors',
                'Nonresidential specialty trade contractors',
                'Building material and garden equipment and supplies dealers',
                'Real estate',
                'Real estate and rental and leasing',
                'Lessors of nonfinancial intangible assets',
            ],
            'ximpim': [
                'Construction materials',
                'Building materials',
                'Lumber',
                'Wood products',
                'Cement',
                'Glass',
                'Ceramic products',
            ],
        },
        'relationship': BLS_ENRICHMENT.housingSectorCorrelation
    },

    'transportation_sector': {
        'description': 'Transportation and warehousing',
        'sector_uri': BLS_ENRICHMENT.TransportationSector,
        'keywords': {
            'cpi': [
                'Transportation',
                'Private transportation',
                'Utilities and public transportation',
                # Vehicles
                'Transportation commodities less motor fuel',
                'New vehicles',
                'New cars',
                'New trucks',
                'Used cars and trucks',
                'New and used motor vehicles',
                'Motor vehicle parts and equipment',
                'Tires',
                'Vehicle accessories other than tires',
                'Vehicle parts and equipment other than tires',
                # Transportation services
                'Transportation services',
                'Leased cars and trucks',
                'Car and truck rental',
                'Motor vehicle maintenance and repair',
                'Motor vehicle body work',
                'Motor vehicle maintenance and servicing',
                'Motor vehicle repair',
                'Motor vehicle insurance',
                'Motor vehicle fees',
                'State motor vehicle registration and license fees',
                'Parking and other fees',
                'Parking fees and tolls',
                # Public transportation
                'Public transportation',
                'Airline fares',
                'Other intercity transportation',
                'Ship fare',
                'Intracity transportation',
                'Intracity mass transit',
            ],
            'ppi': ['Transportation', 'Warehousing', 'Trade', 'Shipping'],
            'eci': ['Transportation', 'Warehousing', 'Trade, transportation'],
            'jolts': ['Transportation', 'Warehousing', 'Truck transportation',
                      'Couriers and messengers', 'Transit', 'Air transportation'],
            'empsit': [
                # From Table B-1
                'Transportation and warehousing',
                'Air transportation',
                'Rail transportation',
                'Water transportation',
                'Truck transportation',
                'Transit and ground passenger transportation',
                'Scenic and sightseeing transportation',
                'Support activities for transportation',
                'Couriers and messengers',
                'Warehousing and storage',
                'Transportation equipment manufacturing',
                'Motor vehicles and parts',
                # From Table A-14 (combined category)
                'Transportation and utilities',
            ],
            'ximpim': [
                'Transportation services',
                'Air freight',
                'Air passenger fares',
                'Ocean freight',
                'Vehicles',
                'Motor vehicles',
                'Automobiles',
                'Trucks',
                'Aircraft',
                'Ships and boats',
                'Railway vehicles',
                'Transportation equipment',
                'Parts and accessories for vehicles',
            ],
        },
        'relationship': BLS_ENRICHMENT.transportationSectorCorrelation
    },

    'goods_services': {
        'description': 'Goods vs Services distinction across datasets',
        'sector_uri': BLS_ENRICHMENT.GoodsServicesSector,
        'keywords': {
            'cpi': [
                'Commodities',
                'Services',
                'Commodities less food and energy commodities',
                'Commodities less food, energy, and used cars and trucks',
                'Commodities less food',
                'Commodities less food and beverages',
                'Services less energy services',
                'Services less rent of shelter',
                'Services less medical care services',
                'Durables',
                'Nondurables',
                'Nondurables less food',
                'Nondurables less food and beverages',
                'Nondurables less food, beverages, and apparel',
                'Nondurables less food and apparel',
            ],
            'ppi': ['Goods', 'Services', 'Final Demand', 'Intermediate Demand',
                    'Processed', 'Unprocessed'],
            'eci': ['Goods-producing', 'Service-providing'],
            'jolts': ['Goods-producing', 'Service-providing', 'Manufacturing',
                      'Trade, transportation, and utilities', 'Professional and business services'],
            'empsit': [
                # From Table B-1
                'Goods-producing',
                'Private service-providing',
                'Durable goods',
                'Nondurable goods',
            ],
            'ximpim': [
                'Goods',
                'Services',
                'Transportation services',
            ],
        },
        'relationship': BLS_ENRICHMENT.goodsServicesRelation
    },

    'manufacturing_sector': {
        'description': 'Manufacturing and production',
        'sector_uri': BLS_ENRICHMENT.ManufacturingSector,
        'keywords': {
            'cpi': [],  # CPI doesn't have manufacturing categories
            'ppi': ['Manufacturing', 'Production', 'Fabrication', 'Processing'],
            'eci': ['Manufacturing', 'Aircraft manufacturing', 'Production'],
            'jolts': ['Manufacturing', 'Durable goods', 'Nondurable goods',
                      'Fabricated metal', 'Machinery', 'Computer and electronic'],
            'empsit': [
                # From Table B-1
                'Manufacturing',
                'Durable goods',
                'Nondurable goods',
                'Wood product manufacturing',
                'Nonmetallic mineral product manufacturing',
                'Primary metal manufacturing',
                'Fabricated metal product manufacturing',
                'Machinery manufacturing',
                'Computer and electronic product manufacturing',
                'Computer and peripheral equipment manufacturing',
                'Communications equipment manufacturing',
                'Semiconductor and other electronic component manufacturing',
                'Navigational, measuring, electromedical, and control instruments manufacturing',
                'Manufacturing and reproducing magnetic and optical media and audio and video equipment manufacturing',
                'Electrical equipment, appliance, and component manufacturing',
                'Transportation equipment manufacturing',
                'Furniture and related product manufacturing',
                'Miscellaneous manufacturing',
                'Food manufacturing',
                'Textile mills',
                'Textile product mills',
                'Apparel manufacturing',
                'Paper manufacturing',
                'Printing and related support activities',
                'Chemical manufacturing',
                'Plastics and rubber products manufacturing',
                # From Table A-13
                'Production occupations',
                'Production, transportation, and material moving occupations',
            ],
            'ximpim': [
                'Manufactured goods',
                'Machinery',
                'Electrical machinery',
                'Industrial machinery',
                'Computers',
                'Telecommunications equipment',
                'Semiconductors',
                'Electronic components',
                'Chemicals',
                'Pharmaceuticals',
                'Plastics',
                'Rubber products',
                'Textiles',
                'Apparel',
                'Footwear',
                'Wood products',
                'Paper products',
                'Printed materials',
                'Metal products',
                'Fabricated metal products',
                'Iron and steel',
                'Nonferrous metals',
            ],
        },
        'relationship': BLS_ENRICHMENT.manufacturingSectorCorrelation
    },

    'retail_sector': {
        'description': 'Retail trade and sales',
        'sector_uri': BLS_ENRICHMENT.RetailSector,
        'keywords': {
            'cpi': [],  # CPI measures prices, not retail activity
            'ppi': ['Trade', 'Wholesale', 'Retail'],
            'eci': ['Retail trade', 'Wholesale trade', 'Trade, transportation'],
            'jolts': ['Retail trade', 'Motor vehicle dealers', 'Furniture stores',
                      'Electronics stores', 'Food and beverage stores', 'General merchandise'],
            'empsit': [
                # From Table B-1
                'Retail trade',
                'Motor vehicle and parts dealers',
                'Automobile dealers',
                'Other motor vehicle dealers',
                'Automotive parts, accessories, and tire retailers',
                'Building material and garden equipment and supplies dealers',
                'Food and beverage retailers',
                'Furniture, home furnishings, electronics, and appliance retailers',
                'Furniture and home furnishings retailers',
                'Electronics and appliance retailers',
                'General merchandise retailers',
                'Department stores',
                'Warehouse clubs, supercenters, and other general merchandise retailers',
                'Health and personal care retailers',
                'Gasoline stations and fuel dealers',
                'Clothing, clothing accessories, shoe, and jewelry retailers',
                'Sporting goods, hobby, musical instrument, book, and miscellaneous retailers',
                'Wholesale trade',
                'Merchant wholesalers, durable goods',
                'Merchant wholesalers, nondurable goods',
                'Wholesale trade agents and brokers',
                # From Table A-13
                'Sales and office occupations',
                'Sales and related occupations',
                # From Table A-14 (combined category)
                'Wholesale and retail trade',
            ],
            'ximpim': [
                'Consumer goods',
                'Household goods',
                'Furniture',
                'Home furnishings',
                'Appliances',
                'Clothing',
                'Footwear',
                'Jewelry',
                'Watches',
                'Toys and games',
                'Sporting goods',
                'Books',
            ],
        },
        'relationship': BLS_ENRICHMENT.retailSectorCorrelation
    },

    'healthcare_sector': {
        'description': 'Healthcare and social assistance',
        'sector_uri': BLS_ENRICHMENT.HealthcareSector,
        'keywords': {
            'cpi': [
                'Medical care',
                # Commodities
                'Medical care commodities',
                'Medicinal drugs',
                'Prescription drugs',
                'Nonprescription drugs',
                'Medical equipment and supplies',
                # Services
                'Medical care services',
                'Professional services',
                'Physicians\' services',
                'Dental services',
                'Eyeglasses and eye care',
                'Services by other medical professionals',
                'Hospital and related services',
                'Hospital services',
                'Inpatient hospital services',
                'Outpatient hospital services',
                'Nursing homes and adult day services',
                'Care of invalids and elderly at home',
                'Health insurance',
            ],
            'ppi': ['Healthcare', 'Medical', 'Hospital'],
            'eci': ['Health care', 'Healthcare', 'Hospitals', 'Nursing', 'Social assistance'],
            'jolts': ['Health care', 'Social assistance', 'Hospitals',
                      'Nursing', 'Ambulatory health care', 'Medical'],
            'empsit': [
                # From Table B-1
                'Health care and social assistance',
                'Health care',
                'Ambulatory health care services',
                'Offices of physicians',
                'Offices of dentists',
                'Offices of other health practitioners',
                'Outpatient care centers',
                'Medical and diagnostic laboratories',
                'Home health care services',
                'Other ambulatory health care services',
                'Hospitals',
                'Nursing and residential care facilities',
                'Skilled nursing care facilities',
                'Residential intellectual and developmental disability, mental health, and substance abuse facilities',
                'Continuing care retirement communities and assisted living facilities for the elderly',
                'Other residential care facilities',
                'Social assistance',
                'Individual and family services',
                'Community food and housing, and emergency and other relief services',
                'Vocational rehabilitation services',
                'Child care services',
                'Private education and health services',
                # From Table A-14 (combined category)
                'Education and health services',
            ],
            'ximpim': [
                'Pharmaceuticals',
                'Medicinal products',
                'Medical equipment',
                'Medical instruments',
                'Surgical instruments',
                'Diagnostic equipment',
            ],
        },
        'relationship': BLS_ENRICHMENT.healthcareSectorCorrelation
    },

    'professional_services_sector': {
        'description': 'Professional and business services',
        'sector_uri': BLS_ENRICHMENT.ProfessionalServicesSector,
        'keywords': {
            'cpi': [],  # CPI doesn't have professional services categories
            'ppi': ['Professional services', 'Business services', 'Consulting'],
            'eci': ['Professional and business services', 'Professional, scientific, and technical',
                    'Administrative and support'],
            'jolts': ['Professional and business services', 'Professional and technical services',
                      'Management', 'Administrative', 'Waste services'],
            'empsit': [
                # From Table B-1
                'Professional and business services',
                'Professional, scientific, and technical services',
                'Legal services',
                'Accounting, tax preparation, bookkeeping, and payroll services',
                'Architectural, engineering, and related services',
                'Specialized design services',
                'Computer systems design and related services',
                'Management, scientific, and technical consulting services',
                'Scientific research and development services',
                'Advertising, public relations, and related services',
                'Other professional, scientific, and technical services',
                'Management of companies and enterprises',
                'Administrative and support and waste management and remediation services',
                'Administrative and support services',
                'Office administrative services',
                'Facilities support services',
                'Employment services',
                'Temporary help services',
                'Business support services',
                'Travel arrangement and reservation services',
                'Investigation and security services',
                'Services to buildings and dwellings',
                'Other support services',
                'Waste management and remediation services',
                # From Table A-13
                'Management, professional, and related occupations',
                'Management, business, and financial operations occupations',
                'Professional and related occupations',
                'Office and administrative support occupations',
            ],
            'ximpim': [
                'Computers',
                'Computer equipment',
                'Semiconductors',
                'Electronic components',
                'Telecommunications equipment',
                'Office machines',
                'Data processing equipment',
            ],
        },
        'relationship': BLS_ENRICHMENT.professionalServicesSectorCorrelation
    },

    'leisure_hospitality_sector': {
        'description': 'Leisure, hospitality, and entertainment',
        'sector_uri': BLS_ENRICHMENT.LeisureHospitalitySector,
        'keywords': {
            'cpi': [
                'Recreation',
                # Commodities
                'Recreation commodities',
                'Video and audio products',
                'Video and audio',
                'Televisions',
                'Other video equipment',
                'Audio equipment',
                'Recorded music and music subscriptions',
                'Pets and pet products',
                'Pets, pet products and services',
                'Pet food and treats',
                'Purchase of pets, pet supplies, accessories',
                'Sporting goods',
                'Sports vehicles including bicycles',
                'Sports equipment',
                'Photographic equipment and supplies',
                'Photographic equipment',
                'Photography',
                'Recreational reading materials',
                'Newspapers and magazines',
                'Recreational books',
                'Other recreational goods',
                'Toys',
                'Toys, games, hobbies and playground equipment',
                'Sewing machines, fabric and supplies',
                'Music instruments and accessories',
                # Services
                'Recreation services',
                'Video and audio services',
                'Cable, satellite, and live streaming television service',
                'Purchase, subscription, and rental of video',
                'Video discs and other media',
                'Subscription and rental of video and video games',
                'Pet services including veterinary',
                'Pet services',
                'Veterinarian services',
                'Photographers and photo processing',
                'Other recreation services',
                'Club membership for shopping clubs, fraternal, or other organizations, or participant sports fees',
                'Admissions',
                'Admission to movies, theaters, and concerts',
                'Admission to sporting events',
                'Fees for lessons or instructions',
            ],
            'ppi': [],  # PPI doesn't have leisure/hospitality categories
            'eci': ['Leisure and hospitality', 'Accommodation and food'],
            'jolts': ['Leisure and hospitality', 'Arts and entertainment',
                      'Accommodation', 'Recreation', 'Amusement'],
            'empsit': [
                # From Table B-1
                'Leisure and hospitality',
                'Arts, entertainment, and recreation',
                'Performing arts, spectator sports, and related industries',
                'Museums, historical sites, and similar institutions',
                'Amusement, gambling, and recreation industries',
                'Accommodation and food services',
                'Accommodation',
                'Food services and drinking places',
            ],
            'ximpim': [],
        },
        'relationship': BLS_ENRICHMENT.leisureHospitalitySectorCorrelation
    },

    'government_sector': {
        'description': 'Government employment',
        'sector_uri': BLS_ENRICHMENT.GovernmentSector,
        'keywords': {
            'cpi': [],
            'ppi': [],
            'eci': ['State and local government', 'Public administration'],
            'jolts': ['Government', 'Federal', 'State', 'Local'],
            'empsit': [
                # From Table B-1
                'Government',
                'Federal',
                'Federal, except U.S. Postal Service',
                'U.S. Postal Service',
                'State government',
                'State government education',
                'State government, excluding education',
                'Local government',
                'Local government education',
                'Local government, excluding education',
                # From Table A-14
                'Government workers',
            ],
            'ximpim': [],
        },
        'relationship': BLS_ENRICHMENT.governmentSectorCorrelation
    },

    'information_sector': {
        'description': 'Information and communications',
        'sector_uri': BLS_ENRICHMENT.InformationSector,
        'keywords': {
            'cpi': [
                'Information and information processing',
                'Information technology, hardware and services',
                'Communication',
            ],
            'ppi': ['Information'],
            'eci': ['Information'],
            'jolts': ['Information', 'Publishing', 'Broadcasting', 'Telecommunications'],
            'empsit': [
                # From Table B-1
                'Information',
                'Motion picture and sound recording industries',
                'Publishing industries',
                'Broadcasting and content providers',
                'Telecommunications',
                'Computing infrastructure providers, data processing, web hosting, and related services',
                'Web search portals, libraries, archives, and other information services',
            ],
            'ximpim': [
                'Telecommunications equipment',
                'Communications equipment',
                'Broadcasting equipment',
                'Printed materials',
                'Books',
                'Newspapers',
                'Periodicals',
            ],
        },
        'relationship': BLS_ENRICHMENT.informationSectorCorrelation
    },

    'financial_sector': {
        'description': 'Financial activities and services',
        'sector_uri': BLS_ENRICHMENT.FinancialSector,
        'keywords': {
            'cpi': [
                'Financial services',
                'Checking account and other bank services',
                'Tax return preparation and other accounting fees',
            ],
            'ppi': ['Financial'],
            'eci': ['Financial activities', 'Finance and insurance', 'Credit intermediation',
                    'Insurance carriers', 'Real estate'],
            'jolts': ['Financial activities', 'Finance', 'Insurance', 'Real estate'],
            'empsit': [
                # From Table B-1
                'Financial activities',
                'Finance and insurance',
                'Monetary authorities-central bank',
                'Credit intermediation and related  activities',
                'Depository credit intermediation',
                'Commercial banking',
                'Nondepository credit intermediation',
                'Activities related to credit intermediation',
                'Securities, commodity contracts, funds, trusts, and other financial vehicles, investments, and related activities',
                'Insurance carriers and related activities',
                'Real estate and rental and leasing',
                'Real estate',
                'Rental and leasing services',
            ],
        },
        'relationship': BLS_ENRICHMENT.financialSectorCorrelation
    },

    'education_sector': {
        'description': 'Educational services',
        'sector_uri': BLS_ENRICHMENT.EducationSector,
        'keywords': {
            'cpi': [
                'Education',
                'Education and communication',
                # Education commodities
                'Education and communication commodities',
                'Educational books and supplies',
                'College textbooks',
                # Education services
                'Education and communication services',
                'Tuition, other school fees, and childcare',
                'College tuition and fees',
                'Elementary and high school tuition and fees',
                'Day care and preschool',
                'Technical and business school tuition and fees',
                # Communication commodities
                'Information technology commodities',
                'Computers, peripherals, and smart home assistants',
                'Computer software and accessories',
                'Telephone hardware, calculators, and other consumer information items',
                'Smartphones',
                # Communication services
                'Postage and delivery services',
                'Postage',
                'Delivery services',
                'Telephone services',
                'Wireless telephone services',
                'Residential telephone services',
                'Internet services and electronic information providers',
            ],
            'ppi': [],
            'eci': ['Educational services', 'Education and health services', 'Elementary and secondary schools',
                    'Junior colleges', 'Colleges', 'Universities', 'Schools'],
            'jolts': ['Educational services'],
            'empsit': [
                # From Table B-1
                'Private educational services',
                'Private education and health services',
                'State government education',
                'Local government education',
                # From Table A-14 (combined category)
                'Education and health services',
            ],
            'ximpim': [
                'Books',
                'Printed materials',
                'Educational materials',
            ],
        },
        'relationship': BLS_ENRICHMENT.educationSectorCorrelation
    },

    'other_services_sector': {
        'description': 'Other services (repair, personal, religious)',
        'sector_uri': BLS_ENRICHMENT.OtherServicesSector,
        'keywords': {
            'cpi': [
                'Other goods and services',
                'Other goods',
                'Other services',
                'Personal care',
                'Personal care products',
                'Hair, dental, shaving, and miscellaneous personal care products',
                'Cosmetics, perfume, bath, nail preparations and implements',
                'Miscellaneous personal goods',
                'Stationery, stationery supplies, gift wrap',
                'Personal care services',
                'Haircuts and other personal care services',
                'Other personal services',
                'Miscellaneous personal services',
                'Legal services',
                'Funeral expenses',
                'Laundry and dry cleaning services',
                'Apparel services other than laundry and dry cleaning',
                'Tobacco and smoking products',
                'Cigarettes',
                'Tobacco products other than cigarettes',
            ],
            'ppi': [],
            'eci': ['Other services'],
            'jolts': ['Other services', 'Repair', 'Personal services'],
            'empsit': [
                # From Table B-1
                'Other services',
                'Repair and maintenance',
                'Personal and laundry services',
                'Religious, grantmaking, civic, professional, and similar organizations',
                # From Table A-13
                'Service occupations',
                'Installation, maintenance, and repair occupations',
            ],
            'ximpim': [],
        },
        'relationship': BLS_ENRICHMENT.otherServicesSectorCorrelation
    },

    'natural_resources_sector': {
        'description': 'Natural resources, farming, fishing, forestry',
        'sector_uri': BLS_ENRICHMENT.NaturalResourcesSector,
        'keywords': {
            'cpi': [],
            'ppi': ['Agriculture', 'Forestry', 'Fishing'],
            'eci': ['Natural resources, construction, and maintenance',
                    'Construction, extraction, farming, fishing, and forestry'],
            'jolts': ['Agriculture', 'Forestry', 'Fishing'],
            'empsit': [
                # From Table B-1
                'Logging',
                # From Table A-13
                'Natural resources, construction, and maintenance occupations',
                'Farming, fishing, and forestry occupations',
                # From Table A-8
                'Agriculture and related industries',
                # From Table A-14
                'Agriculture and related private wage and salary workers',
            ],
            'ximpim': [
                'Agricultural products',
                'Forestry products',
                'Fish and seafood',
                'Timber',
                'Logs',
                'Wood',
                'Cork',
                'Animal products',
                'Hides and skins',
                'Crude fertilizers',
                'Ores',
                'Metal ores',
                'Minerals',
            ],
        },
        'relationship': BLS_ENRICHMENT.naturalResourcesSectorCorrelation
    },

    'construction_trades_sector': {
        'description': 'Construction and extraction trades',
        'sector_uri': BLS_ENRICHMENT.ConstructionTradesSector,
        'keywords': {
            'cpi': [],
            'ppi': ['Construction'],
            'eci': ['Construction', 'Installation, maintenance, and repair'],
            'jolts': ['Construction'],
            'empsit': [
                # From Table A-13
                'Construction and extraction occupations',
                'Natural resources, construction, and maintenance occupations',
            ],
            'ximpim': [
                'Construction materials',
                'Building materials',
            ],
        },
        'relationship': BLS_ENRICHMENT.constructionTradesSectorCorrelation
    },

    'apparel_sector': {
        'description': 'Apparel and clothing',
        'sector_uri': BLS_ENRICHMENT.ApparelSector,
        'keywords': {
            'cpi': [
                'Apparel',
                'Apparel less footwear',
                # Men's and boys'
                'Men\'s and boys\' apparel',
                'Men\'s apparel',
                'Men\'s suits, sport coats, and outerwear',
                'Men\'s underwear, nightwear, swimwear, and accessories',
                'Men\'s shirts and sweaters',
                'Men\'s pants and shorts',
                'Boys\' apparel',
                # Women's and girls'
                'Women\'s and girls\' apparel',
                'Women\'s apparel',
                'Women\'s outerwear',
                'Women\'s dresses',
                'Women\'s suits and separates',
                'Women\'s underwear, nightwear, swimwear, and accessories',
                'Girls\' apparel',
                # Footwear
                'Footwear',
                'Men\'s footwear',
                'Boys\' and girls\' footwear',
                'Women\'s footwear',
                # Other
                'Infants\' and toddlers\' apparel',
                'Jewelry and watches',
                'Watches',
                'Jewelry',
            ],
            'ppi': [],
            'eci': [],
            'jolts': [],
            'empsit': [],
            'ximpim': [],
        },
        'relationship': BLS_ENRICHMENT.apparelSectorCorrelation
    },
}