"""
BLS Sector Patterns - Economic sector definitions and keywords
"""
from glue_jobs.utils.rdf_utils import BLS_ENRICHMENT

BLS_SECTOR_PATTERNS = {
    'food_sector': {
        'description': 'Food production, distribution, and consumption chain',
        'sector_uri': BLS_ENRICHMENT.FoodSector,
        'keywords': {
            'cpi': [
                # Main food categories
                'Food',
                'Food at home',
                'Food away from home',
                'Cereals and bakery products',
                'Cereals and cereal products',
                'Flour and prepared flour mixes',
                'Breakfast cereal',
                'Rice, pasta, cornmeal',
                'Rice',
                'Bakery products',
                'Bread',
                'White bread',
                'Bread other than white',
                'Fresh biscuits, rolls, muffins',
                'Cakes, cupcakes, and cookies',
                'Cookies',
                'Fresh cakes and cupcakes',
                'Other bakery products',
                'Fresh sweetrolls, coffeecakes, doughnuts',
                'Crackers, bread, and cracker products',
                'Frozen and refrigerated bakery products, pies, tarts, turnovers',
                'Meats, poultry, fish, and eggs',
                'Meats, poultry, and fish',
                'Meats',
                'Beef and veal',
                'Uncooked ground beef',
                'Uncooked beef roasts',
                'Uncooked beef steaks',
                'Uncooked other beef and veal',
                'Pork',
                'Bacon, breakfast sausage, and related products',
                'Bacon and related products',
                'Breakfast sausage and related products',
                'Ham',
                'Ham, excluding canned',
                'Pork chops',
                'Other pork including roasts, steaks, and ribs',
                'Other meats',
                'Frankfurters',
                'Lunchmeats',
                'Poultry',
                'Chicken',
                'Fresh whole chicken',
                'Fresh and frozen chicken parts',
                'Other uncooked poultry including turkey',
                'Fish and seafood',
                'Fresh fish and seafood',
                'Processed fish and seafood',
                'Shelf stable fish and seafood',
                'Frozen fish and seafood',
                'Eggs',
                'Dairy and related products',
                'Milk',
                'Fresh whole milk',
                'Fresh milk other than whole',
                'Cheese and related products',
                'Ice cream and related products',
                'Other dairy and related products',
                'Fruits and vegetables',
                'Fresh fruits and vegetables',
                'Fresh fruits',
                'Apples',
                'Bananas',
                'Citrus fruits',
                'Oranges, including tangerines',
                'Other fresh fruits',
                'Fresh vegetables',
                'Potatoes',
                'Lettuce',
                'Tomatoes',
                'Other fresh vegetables',
                'Processed fruits and vegetables',
                'Canned fruits and vegetables',
                'Canned fruits',
                'Canned vegetables',
                'Frozen fruits and vegetables',
                'Frozen vegetables',
                'Other processed fruits and vegetables including dried',
                'Dried beans, peas, and lentils',
                'Nonalcoholic beverages and beverage materials',
                'Juices and nonalcoholic drinks',
                'Carbonated drinks',
                'Frozen noncarbonated juices and drinks',
                'Nonfrozen noncarbonated juices and drinks',
                'Beverage materials including coffee and tea',
                'Coffee',
                'Roasted coffee',
                'Instant coffee',
                'Other beverage materials including tea',
                'Other food at home',
                'Sugar and sweets',
                'Sugar and sugar substitutes',
                'Candy and chewing gum',
                'Other sweets',
                'Fats and oils',
                'Butter and margarine',
                'Butter',
                'Margarine',
                'Salad dressing',
                'Other fats and oils including peanut butter',
                'Peanut butter',
                'Other foods',
                'Soups',
                'Frozen and freeze dried prepared foods',
                'Snacks',
                'Spices, seasonings, condiments, sauces',
                'Salt and other seasonings and spices',
                'Olives, pickles, relishes',
                'Sauces and gravies',
                'Other condiments',
                'Baby food and formula',
                'Other miscellaneous foods',
                'Prepared salads',
                'Full service meals and snacks',
                'Limited service meals and snacks',
                'Food at employee sites and schools',
                'Food at elementary and secondary schools',
                'Food from vending machines and mobile vendors',
                'Other food away from home',
                'Alcoholic beverages',
                'Alcoholic beverages at home',
                'Beer, ale, and other malt beverages at home',
                'Distilled spirits at home',
                'Whiskey at home',
                'Distilled spirits, excluding whiskey, at home',
                'Wine at home',
                'Alcoholic beverages away from home',
                'Beer, ale, and other malt beverages away from home',
                'Wine away from home',
                'Distilled spirits away from home',
                'Food and beverages',
                'Domestically produced farm food',
            ],
            'ppi': [
                # Final Demand Foods
                'Foods',
                'Final demand foods',
                'Finished consumer foods',
                'Finished consumer foods, crude',
                'Finished consumer foods, processed',
                'Government purchased foods',
                'Foods for export',
                # Specific food products
                'Fresh fruits and melons',
                'Fresh and dry vegetables',
                'Grains',
                'Eggs for fresh use',
                'Oilseeds',
                'Bakery products',
                'Milled rice',
                'Pasta products',
                'Beef and veal',
                'Pork',
                'Processed young chickens',
                'Processed turkeys',
                'Finfish and shellfish',
                'Dairy products',
                'Processed fruits and vegetables',
                'Confectionery end products',
                'Soft drinks',
                'Roasted coffee',
                'Shortening and cooking oils',
                'Frozen specialty food',
                'Alcoholic beverages',
                'Pet food',
                # Intermediate demand foods
                'Foodsandfeeds',
                'Foodstuffsandfeedstuffs',
                'Processed foods and feeds',
                'Meats',
                'Processed poultry',
                'Refined sugar and byproducts',
                'Fats and oils',
                'Prepared animal feeds',
                'Unprocessed foodstuffs and feedstuffs',
                'Wheat',
                'Corn',
                'Slaughter cattle',
                'Slaughter hogs',
                'Slaughter chickens',
                'Slaughter turkeys',
                'Slaughter poultry',
                'Raw milk',
                'Hay and hayseeds',
                'Raw cane sugar and byproducts',
                'Unprocessed and packaged fish',
                # Food wholesaling and retailing
                'Food wholesaling',
                'Food and alcohol wholesaling',
                'Food and alcohol retailing',
                # Food services
                'Food and beverages for immediate consumption services (partial)',
                # Food manufacturing materials
                'Materials for food manufacturing',
                'Food products machinery',
            ],
            'eci': ['Food services', 'Accommodation and food', 'Food service'],
            'jolts': [
                'Accommodation and food services',
                'Food services',
            ],
            'empsit': [
                'Food manufacturing',
                'Food and beverage retailers',
                'Food services and drinking places',
                'Accommodation and food services',
                'Beverage, tobacco, and leather',
            ],
            'ximpim': [
                # General food categories
                'Food',
                'Foodstuffs',
                'Foods, feeds, & beverages',
                'Agricultural foods, feeds & beverages, excluding distilled beverages',
                'Nonagricultural foods (fish, distilled beverages)',
                # Live animals and animal products
                'Live animals; animal products',
                'Meat and edible meat offal',
                'Meat & edible meat offal (Dec. 2006=100)',
                'Fish and crustaceans, molluscs and other aquatic invertebrates',
                'Fish and crustaceans, mollusks and aquatic invertebrates (Jan. 2025=100)',
                'Dairy products, eggs, and honey (Jan. 2025=100)',
                'Dairy products, eggs and honey (Jan. 2025=100)',
                'Products of animal origin, nesoi (Jan. 2025=100)',
                # Vegetable products
                'Vegetable products',
                'Live trees & plants; bulbs, roots; cut flowers and ornamental foliage (Jan. 2025=100)',
                'Edible vegetables, roots, and tubers',
                'Edible Vegetables (Jan. 2025=100)',
                'Edible fruit and nuts; peel of citrus fruit or melons',
                'Edible fruit and nuts; citrus or melon peels',
                'Coffee, tea, mate and spices',
                'Cereals (Jan. 2025=100)',
                'Cereals',
                'Milling industry products; malt; starches; inulin; wheat gluten (Jan. 2025=100)',
                'Oilseeds & misc grains, seeds, plants, straw & fodder (Jan. 2025=100)',
                'Oilseeds and misc. grains, seeds, fruits, plants, straw and fodder',
                # Fats and oils
                'Animal or vegetable fats and oils (Dec. 2009=100)',
                'Animal or vegetable fats and oils (Jan. 2025=100)',
                'Animal or vegetable fats and oils and their cleavage products; prepared (Dec. 2023=100)',
                'Animal or vegetable fats & oils (Jan. 2025=100)',
                # Prepared foodstuffs
                'Prepared foodstuffs, beverages, and tobacco',
                'Sugars and sugar confectionary (Dec. 2021=100)',
                'Sugars and sugar confectionary (Jan. 2025=100)',
                'Cocoa and cocoa preparations (Dec. 2009=100)',
                'Cocoa and cocoa preparations (Jan. 2025=100)',
                'Preparations of cereals, flour, starch or milk; bakers\' wares (Dec. 2023=100)',
                'Preparations of vegetables, fruit, nuts, or other parts of plants (Jan. 2025=100)',
                'Preparations of vegetables, fruit, nuts or other parts of plants (Jan. 2025=100)',
                'Edible preps of meat, of fish, or of aquatic invertebrates (Jan. 2025=100)',
                'Miscellaneous edible preparations (Dec. 2022=100)',
                'Miscellaneous edible preparations (Dec. 2017=100)',
                # Beverages
                'Beverages',
                'Beverages, spirits, and vinegar',
                'Beverages, spirits, and vinegar (Dec. 2024=100)',
                # Animal feed
                'Residues and waste from the food industries; prepared animal feed (Jan. 2025=100)',
                'Residues and waste from the food industries; prepared animal feed',
                # Tobacco
                'Tobacco and manufactured tobacco substitutes (Jan. 2025=100)',
                # Manufacturing categories
                'Food manufacturing',
                'Beverage and tobacco product manufacturing',
                # Agriculture
                'Agriculture, forestry, fishing and hunting',
                'Crop production',
                'Animal production (Dec. 2022=100)',
                'Animal production (Jan. 2025=100)',
                'Fishing, hunting and trapping (Jan. 2025=100)',
                'Agricultural commodities',
            ],
            'laus': [],  # LAUS doesn't have food-specific categories
        },
        'relationship': BLS_ENRICHMENT.foodSectorCorrelation
    },

    'energy_sector': {
        'description': 'Energy production, distribution, and consumption',
        'sector_uri': BLS_ENRICHMENT.EnergySector,
        'keywords': {
            'cpi': [
                'Energy',
                'Energy commodities',
                'Energy services',
                'Gasoline (all types)',
                'Gasoline, unleaded regular',
                'Gasoline, unleaded midgrade',
                'Gasoline, unleaded premium',
                'Fuel oil',
                'Fuel oil and other fuels',
                'Propane, kerosene, and firewood',
                'Motor fuel',
                'Other motor fuels',
                'Motor oil, coolant, and fluids',
                'Electricity',
                'Utility (piped) gas service',
                'Fuels and utilities',
                'Household energy',
            ],
            'ppi': [
                # Final demand energy
                'Energy',
                'Energygood',
                'Final demand energy',
                'Finished consumer energy goods',
                'Government purchased energy',
                'Energy for export',
                # Specific energy products
                'Natural gas liquids',
                'Residential electric power',
                'Commercial electric power',
                'Industrial electric power',
                'Residential natural gas',
                'Commercial natural gas',
                'Industrial natural gas',
                'Natural gas to electric utilities',
                'Natural gas',
                'Gasoline',
                'Home heating oil and distillates',
                'No. 2 diesel fuel',
                'Jet fuel',
                'Residual fuels',
                'Finished lubricants',
                'Lubricating oil base stocks',
                'Asphalt',
                # Intermediate demand energy
                'Energymaterials',
                'Processed energy goods',
                'Unprocessed energy materials',
                'Processed fuels and lubricants for intermediate demand',
                'Processed fuels and lubricants to manufacturing industries',
                'Processed fuels and lubricants to nonmanufacturing industries',
                # Unprocessed energy
                'Unprocessed fuel',
                'Unprocessed fuel to manufacturing industries',
                'Unprocessed fuel to nonmanufacturing industries',
                'Coal',
                'Crude petroleum',
                # Energy retailing
                'Fuels and lubricants retailing',
            ],
            'eci': ['Utilities', 'Mining', 'Oil and gas'],
            'jolts': ['Mining and logging'],
            'empsit': [
                'Mining and logging',
                'Oil and gas extraction',
                'Coal mining',
                'Mining, quarrying, and oil and gas extraction',
                'Mining (except oil and gas)',
                'Metal ore mining',
                'Nonmetallic mineral mining',
                'Support activities for mining',
                'Utilities',
                'Petroleum and coal products manufacturing',
                'Gasoline stations and fuel dealers',
                'Pipeline transportation',
            ],
            'ximpim': [
                'Fuel',
                'Petroleum',
                'Crude oil',
                'Refined petroleum products',
                'Natural gas',
                'Coal',
                'Energy',
                'Mineral fuels',
                'Petroleum oils',
                'Gas oils',
                'Fuel oils',
                'Liquefied propane and butane',
                'Petroleum gases',
            ],
            'laus': ['Mining and logging'],
        },
        'relationship': BLS_ENRICHMENT.energySectorCorrelation
    },

    'housing_sector': {
        'description': 'Housing, construction, and shelter',
        'sector_uri': BLS_ENRICHMENT.HousingSector,
        'keywords': {
            'cpi': [
                'Housing',
                'Shelter',
                'Rent of shelter',
                'Rent of primary residence',
                'Owners\' equivalent rent of residences',
                'Owners\' equivalent rent of primary residence',
                'Lodging away from home',
                'Housing at school, excluding board',
                'Other lodging away from home including hotels and motels',
                'Tenants\' and household insurance',
                'Water and sewer and trash collection services',
                'Water and sewerage maintenance',
                'Garbage and trash collection',
                'Household operations',
                'Domestic services',
                'Gardening and lawncare services',
                'Moving, storage, freight expense',
                'Repair of household items',
                'Household furnishings and supplies',
                'Household furnishings and operations',
                'Window and floor coverings and other linens',
                'Floor coverings',
                'Window coverings',
                'Other linens',
                'Furniture and bedding',
                'Bedroom furniture',
                'Living room, kitchen, and dining room furniture',
                'Other furniture',
                'Appliances',
                'Major appliances',
                'Laundry equipment',
                'Other appliances',
                'Other household equipment and furnishings',
                'Clocks, lamps, and decorator items',
                'Indoor plants and flowers',
                'Dishes and flatware',
                'Nonelectric cookware and tableware',
                'Tools, hardware, outdoor equipment and supplies',
                'Tools, hardware and supplies',
                'Outdoor equipment and supplies',
                'Housekeeping supplies',
                'Household cleaning products',
                'Household paper products',
                'Miscellaneous household products',
            ],
            'ppi': [
                # Construction
                'Construction',
                'Final demand construction',
                'Construction for private capital investment',
                'Construction for government',
                'Construction for intermediate demand',
                'Inputs to stage 4 construction producers',
                'Inputs to stage 3 construction producers',
                'Inputs to stage 2 construction producers',
                'Inputs to stage 1 construction producers',
                # Specific construction types
                'New warehouse building construction',
                'New school building construction',
                'New office building construction',
                'New industrial building construction',
                'New health care building construction',
                'Maintenance and repair of non-residential buildings (partial)',
                # Construction materials
                'Materials and components for construction',
                'Materials for construction',
                'Components for construction',
                'Plastic construction products',
                'Softwood lumber',
                'Hardwood lumber',
                'Lumber',
                'Millwork',
                'Plywood',
                'Cement',
                'Concrete products',
                'Concrete ingredients and related products',
                'Asphalt felts and coatings',
                'Prepared asphalt, tar roofing and siding products',
                'Paving mixtures and blocks',
                'Construction sand, gravel, and crushed stone',
                'Flat glass',
                # Household products
                'Household furniture',
                'Commercial furniture',
                'Floor coverings',
                'Household appliances',
                'Home electronic equipment',
                'Lawn and garden equipment excl. garden tractors',
                'Textile house furnishings',
                'Soaps and detergents',
                'Cleaning and polishing products',
                'Sanitary paper products',
                # Real estate
                'Residential property sales and leases, brokerage fees and commissions',
                'Nonresidential real estate rents',
                'Nonresidential property sales and leases',
                'Residential property management fees',
                'Nonresidential property management fees',
                # Wholesaling and retailing
                'Furnishings wholesaling',
                'Building materials, paint, and hardware wholesaling',
                'Hardware, building materials, and supplies retailing',
                'Hardware, building material, and supplies retailing',
                'Furniture retailing',
                'Flooring and floor coverings retailing',
                'Major household appliances retailing',
                'Cleaning supplies and paper products retailing',
                'Lawn, garden, and farm equipment and supplies retailing',
            ],
            'eci': ['Construction', 'Real estate', 'Rental', 'Leasing'],
            'jolts': ['Construction', 'Real estate and rental and leasing'],
            'empsit': [
                'Construction',
                'Construction of buildings',
                'Residential building construction',
                'Nonresidential building construction',
                'Heavy and civil engineering construction',
                'Specialty trade contractors',
                'Residential specialty trade contractors',
                'Nonresidential specialty trade contractors',
                'Building material and garden equipment and supplies dealers',
                'Real estate',
                'Real estate and rental and leasing',
                'Lessors of nonfinancial intangible assets',
            ],
            'ximpim': [
                # Building materials
                'Construction materials',
                'Building materials',
                'Selected building materials (Jan. 2025=100)',
                'Selected building materials',
                # Wood products
                'Lumber',
                'Wood products',
                'Wood, wood charcoal, cork, straw, basketware and wickerwork (Jan. 2025=100)',
                'Wood and articles of wood; wood charcoal (Jan. 2025=100)',
                'Wood, wood charcoal, cork, straw, baskets and wickerwork (Dec. 2014=100)',
                'Wood and articles of wood; wood charcoal (Dec. 2023=100)',
                'Wood product manufacturing (Jan. 2025=100)',
                'Wood product manufacturing (Dec. 2017=100)',
                'Forestry and logging (Jan. 2025=100)',
                # Stone, cement, glass
                'Cement',
                'Glass',
                'Stone, plaster, cement, asbestos, ceramics, glass etc.',
                'Articles of stone, plaster, cement, asbestos, or mica (Dec. 2020=100)',
                'Ceramic products (Dec. 2024=100)',
                'Ceramic products',
                'Glass and glassware (Dec. 2021=100)',
                'Glass and glassware (Dec. 2019=100)',
                'Salt; sulfur; earths and stone; plaster materials, lime & cement (Jan. 2025=100)',
                'Nonmetallic mineral product manufacturing',
                # Furniture
                'Furniture',
                'Furniture & stuffed furnishings; lamps & lighting fittings, nesoi; prefab bldgs',
                'Furniture; stuffed furnishings; lamps and lighting fittings nesoi',
                'Furniture and related product manufacturing',
                'Furniture and related product manufacturing (Dec. 2023=100)',
            ],
            'laus': ['Construction'],
        },
        'relationship': BLS_ENRICHMENT.housingSectorCorrelation
    },

    'transportation_sector': {
        'description': 'Transportation and warehousing',
        'sector_uri': BLS_ENRICHMENT.TransportationSector,
        'keywords': {
            'cpi': [
                'Transportation',
                'Private transportation',
                'Utilities and public transportation',
                'Transportation commodities less motor fuel',
                'New vehicles',
                'New cars',
                'New trucks',
                'Used cars and trucks',
                'New and used motor vehicles',
                'Motor vehicle parts and equipment',
                'Tires',
                'Vehicle accessories other than tires',
                'Vehicle parts and equipment other than tires',
                'Transportation services',
                'Leased cars and trucks',
                'Car and truck rental',
                'Motor vehicle maintenance and repair',
                'Motor vehicle body work',
                'Motor vehicle maintenance and servicing',
                'Motor vehicle repair',
                'Motor vehicle insurance',
                'Motor vehicle fees',
                'State motor vehicle registration and license fees',
                'Parking and other fees',
                'Parking fees and tolls',
                'Public transportation',
                'Airline fares',
                'Other intercity transportation',
                'Ship fare',
                'Intracity transportation',
                'Intracity mass transit',
            ],
            'ppi': [
                # Transportation services
                'Transportationandwarehousing',
                'Transportation and warehousing services for intermediate demand',
                'Final demand transportation and warehousing services',
                # Freight transportation
                'Rail transportation of freight and mail',
                'Truck transportation of freight',
                'Water transportation of freight',
                'Air transportation of freight',
                'Pipeline transportation',
                # Passenger transportation
                'Transportation of passengers for final demand',
                'Transportation of private passengers',
                'Transportation of government passengers',
                'Transportation of passengers for export',
                'Transportation of passengers for intermediate demand',
                'Transportation of passengers for manufacturing industries',
                'Transportation of passengers for nonmanufacturing industries',
                'Rail transportation of passengers',
                'Airline passenger services',
                'Transportation of passengers (partial)',
                # Goods transportation and warehousing
                'Transportation and warehousing of goods for final demand',
                'Transportation and warehousing of finished goods',
                'Transportation and warehousing of personal consumption goods',
                'Transportation and warehousing of private capital equipment',
                'Transportation and warehousing of government purchased goods',
                'Transportation and warehousing of exports',
                'Transportation and warehousing of goods for intermediate demand',
                'Transportation and warehousing of goods for manufacturing industries',
                'Transportation and warehousing of goods for nonmanufacturing industries',
                # Postal and courier
                'Courier, messenger, and U.S. postal services',
                'U.S. Postal Service',
                'Courier and messenger services, except air mail',
                'Air mail and package delivery services, excluding by USPS',
                # Related services
                'Services related to water transportation',
                'Arrangement of freight and cargo',
                'Freight forwarding',
                'Warehousing, storage, and related services',
                # Vehicles and parts
                'Passenger cars',
                'Light motor trucks',
                'Heavy motor trucks',
                'Motor vehicles parts',
                'Motor vehicle parts',
                'Truck trailers',
                'Travel trailers and campers',
                'Aircraft',
                'Aircraft engines and engine parts',
                'Aircraft parts and auxiliary equipment, n.e.c.',
                'Ships',
                'Railroad equipment',
                'Tires',
                # Vehicle services
                'Passenger car rental',
                'Truck, utility trailer, and RV rental and leasing',
                'Motor vehicle repair and maintenance (partial)',
                'Aircraft repair and maintenance',
                'Aircraft repair maintenance',
                # Wholesaling and retailing
                'Automobiles retailing (partial)',
                'Automotive parts, including tires, retailing',
                'RVs, trailers, and campers retailing',
                'Arrangement of flights (partial)',
                'Arrangement of vehicle rentals and lodging',
                'Arrangement of cruises and tours',
            ],
            'eci': ['Transportation', 'Warehousing', 'Trade, transportation'],
            'jolts': ['Trade, transportation, and utilities', 'Transportation, warehousing, and utilities'],
            'empsit': [
                'Transportation and warehousing',
                'Air transportation',
                'Rail transportation',
                'Water transportation',
                'Truck transportation',
                'Transit and ground passenger transportation',
                'Scenic and sightseeing transportation',
                'Support activities for transportation',
                'Couriers and messengers',
                'Warehousing and storage',
                'Transportation equipment manufacturing',
                'Motor vehicles and parts',
                'Transportation and utilities',
            ],
            'ximpim': [
                # Transportation services
                'Transportation services',
                'Air Freight',
                'Import Air Freight',
                'Export Air Freight',
                'Inbound Air Freight',
                'Outbound Air Freight',
                'Air Passenger Fares',
                'Import Air Passenger Fares',
                'Export Air Passenger Fares',
                # Vehicles and transportation equipment
                'Vehicles',
                'Motor vehicles',
                'Automobiles',
                'Vehicles, aircraft, vessels and associated transport equipment',
                'Motor vehicles and their parts',
                'Automotive vehicles, parts & engines',
                'Automotive vehicles, parts and engines, 2 digit (Dec. 2023=100)',
                'Vehicles-passenger (Dec. 2023=100)',
                'Transportation equipment excluding motor vehicles (Dec. 2001=100)',
                'Transportation equipment manufacturing',
                # Aircraft
                'Aircraft',
                'Aircraft, spacecraft, and parts thereof (Dec. 2020=100)',
                # Ships and boats
                'Ships and boats',
                # Railway vehicles
                'Railway vehicles',
                # Parts and accessories
                'Transportation equipment',
                'Parts and accessories for vehicles',
            ],
            'laus': ['Trade, transportation, and utilities'],
        },
        'relationship': BLS_ENRICHMENT.transportationSectorCorrelation
    },

    'goods_services': {
        'description': 'Goods vs Services distinction across datasets',
        'sector_uri': BLS_ENRICHMENT.GoodsServicesSector,
        'keywords': {
            'cpi': [
                'Commodities',
                'Services',
                'Commodities less food and energy commodities',
                'Commodities less food, energy, and used cars and trucks',
                'Commodities less food',
                'Commodities less food and beverages',
                'Services less energy services',
                'Services less rent of shelter',
                'Services less medical care services',
                'Durables',
                'Nondurables',
                'Nondurables less food',
                'Nondurables less food and beverages',
                'Nondurables less food, beverages, and apparel',
                'Nondurables less food and apparel',
            ],
            'ppi': [
                # Final demand
                'Final demand goods',
                'Final demand services',
                'Final demand goods less foods and energy',
                'Finished goods less foods and energy',
                'Finished consumer goods less foods and energy',
                'Nondurable consumer goods less foods and energy',
                'Durable consumer goods',
                # Intermediate demand
                'Processed goods',
                'Processed goods for intermediate demand',
                'Unprocessed goods',
                'Unprocessed goods for intermediate demand',
                'Services',
                'Services for intermediate demand',
                # Goods inputs
                'Goodsinputs',
                'Goods',
                'Goods excluding foods and energy',
                'Total goods inputs to stage 4 intermediate demand',
                'Total goods inputs to stage 3 intermediate demand',
                'Total goods inputs to stage 2 intermediate demand',
                'Total goods inputs to stage 1 intermediate demand',
                # Services inputs
                'Servicesinputs',
                'Services less trade, transportation, and warehousing',
                'Total services inputs to stage 4 intermediate demand',
                'Total services inputs to stage 3 intermediate demand',
                'Total services inputs to stage 2 intermediate demand',
                'Total services inputs to stage 1 intermediate demand',
                # Special groupings
                'Finished goods',
                'Finished goods less energy',
                'Finished goods, excluding foods',
                'Finished services',
                'Finished goods plus finished distributive services',
                'Personal consumption goods (finished consumer goods)',
                'Personal consumption services',
            ],
            'eci': ['Goods-producing', 'Service-providing'],
            'jolts': [],
            'empsit': [
                'Goods-producing',
                'Private service-providing',
                'Durable goods',
                'Nondurable goods',
            ],
             'ximpim': [
                # General goods categories
                'Goods',
                'Services',
                'All commodities',
                # Consumer goods
                'Consumer goods, excluding automotives',
                'Nondurables, manufactured',
                'Durables, manufactured',
                'Nonmanufactured consumer goods',
                'Nonmanufactured consumer goods (Dec. 2018=100)',
                # Industrial supplies
                'Industrial supplies & materials',
                'Industrial supplies & materials excluding petroleum',
                'Industrial supplies & materials, durable',
                'Industrial supplies & materials nondurable excluding petroleum',
                'Industrial supplies & materials, nondurable',
                'Agricultural industrial supplies & materials',
                'Nonagricultural industrial supplies & materials',
                # Capital goods
                'Capital goods',
                # Durable vs nondurable
                'Materials associated with nondurable supplies & materials',
                'Unfinished metals related to durable goods',
                'Finished metals related to durable goods',
                'Nonmetals related to durable goods (Jan. 2025=100)',
            ],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.goodsServicesRelation
    },

    'manufacturing_sector': {
        'description': 'Manufacturing and production',
        'sector_uri': BLS_ENRICHMENT.ManufacturingSector,
        'keywords': {
            'cpi': [],
            'ppi': [
                # Manufacturing categories
                'Manufacturing',
                'Materials and components for manufacturing',
                'Materials for manufacturing',
                'Materials for food manufacturing',
                'Materials for nondurable manufacturing',
                'Materials for durable manufacturing',
                'Components for manufacturing',
                'Components for nondurable manufacturing',
                'Components for durable manufacturing',
                # Private capital equipment
                'Private capital equipment',
                'Private capital equipment for manufacturing industries',
                'Private capital equipment for nonmanufacturing industries',
                # Chemicals
                'Industrial chemicals',
                'Basic inorganic chemicals',
                'Basic organic chemicals',
                'Prepared paint',
                'Paint materials',
                'Medicinal and botanical chemicals',
                'Biological products, including diagnostics',
                'Pharmaceutical preparations',
                'Fats and oils, inedible',
                'Nitrogenates',
                'Phosphates',
                'Other agricultural chemicals',
                'Agricultural chemicals and chemical products',
                'Chemicals and allied products wholesaling',
                # Plastics and rubber
                'Plastic resins and materials',
                'Industrial gases',
                'Adhesives and sealants',
                'Synthetic rubber',
                'Plastic products',
                'Unsupported plastic film, sheet, other shapes',
                'Unsupported plastic film, sheet, and other shapes',
                'Parts for manufacturing from plastics',
                'Plastic packaging products',
                # Paper products
                'Paper',
                'Paperboard',
                'Paperboard, excluding corrugated paperboard',
                'Paper boxes and containers',
                'Building paper and board',
                'Converted paper and paperboard products',
                'Commercial printing',
                'Recyclable paper',
                'Paper and plastics products wholesaling',
                # Metals
                'Foundry and forge shop products',
                'Steel mill products',
                'Primary nonferrous metals',
                'Secondary nonferrous metals',
                'Aluminum mill shapes',
                'Copper and brass mill shapes',
                'Nonferrous wire and cable',
                'Nonferrous foundry shop products',
                'Nonferrous mill shapes',
                'Metal containers',
                'Hardware',
                'Plumbing fixtures and brass fittings',
                'Heating equipment',
                'Fabricated structural metal products',
                'Structural, architectural, and pre-engineered metal products',
                'Bolts, nuts, screws, rivets, and washers',
                'Lighting fixtures',
                'Fabricated ferrous wire products',
                'Other miscellaneous metal products',
                'Iron and steel scrap',
                'Nonferrous scrap',
                'Iron ores',
                'Nonferrous metal ores',
                'Copper base scrap',
                'Aluminum base scrap',
                'Metals, minerals, and ores wholesaling',
                # Machinery and equipment
                'Agricultural machinery and equipment',
                'Construction machinery and equipment',
                'Metal cutting machine tools',
                'Metal forming machine tools',
                'Tools, dies, jigs, fixtures, and industrial molds',
                'Pumps, compressors, and equipment',
                'Industrial material handling equipment',
                'Food products machinery',
                'Paper industries machinery',
                'Printing trades machinery and equipment',
                'Oil field and gas field machinery',
                'Mining machinery and equipment',
                'Fluid power equipment',
                'Mechanical power transmission equipment',
                'Air conditioning and refrigeration equipment',
                'Metal valves, except fluid power',
                'Ball and roller bearings',
                'General purpose machinery and equipment',
                'Machinery and equipment parts and supplies wholesaling',
                'Machinery and vehicle wholesaling',
                # Electrical equipment
                'Transformers and power regulators',
                'Wiring devices',
                'Motors, generators, motor generator sets',
                'Switchgear, switchboard, and industrial controls equip.',
                'Electrical machinery and equipment',
                'Miscellaneous electrical machinery and equipment',
                # Electronics
                'Electronic computers and computer equipment',
                'Communication and related equipment',
                'Electronic components and accessories',
                'X-ray and electromedical equipment',
                # Engines
                'Internal combustion engines',
                # Machine shops
                'Machine shop products',
                # Textiles
                'Synthetic fibers',
                'Processed yarns and threads',
                'Finished fabrics',
                'Raw cotton',
                # Other manufacturing
                'Consumer, institutional, and commercial products, n.e.c.',
                'Metal treatment services',
            ],
            'eci': ['Manufacturing', 'Aircraft manufacturing', 'Production'],
            'jolts': ['Manufacturing', 'Durable goods', 'Nondurable goods'],
            'empsit': [
                'Manufacturing',
                'Durable goods',
                'Nondurable goods',
                'Wood product manufacturing',
                'Nonmetallic mineral product manufacturing',
                'Primary metal manufacturing',
                'Fabricated metal product manufacturing',
                'Machinery manufacturing',
                'Computer and electronic product manufacturing',
                'Computer and peripheral equipment manufacturing',
                'Communications equipment manufacturing',
                'Semiconductor and other electronic component manufacturing',
                'Navigational, measuring, electromedical, and control instruments manufacturing',
                'Manufacturing and reproducing magnetic and optical media and audio and video equipment manufacturing',
                'Electrical equipment, appliance, and component manufacturing',
                'Transportation equipment manufacturing',
                'Furniture and related product manufacturing',
                'Miscellaneous manufacturing',
                'Food manufacturing',
                'Textile mills',
                'Textile product mills',
                'Paper manufacturing',
                'Printing and related support activities',
                'Chemical manufacturing',
                'Plastics and rubber products manufacturing',
                'Production occupations',
                'Production, transportation, and material moving occupations',
            ],
             'ximpim': [
                # General manufacturing
                'Manufactured goods',
                'Manufacturing',
                'Manufacturing, part 1',
                'Manufacturing, part 2',
                'Manufacturing, part 3',
                'Nonmanufacturing',
                # Machinery
                'Machinery',
                'Machinery and mechanical appliances; parts thereof',
                'Nonelectrical machinery',
                'Machinery manufacturing',
                # Electrical machinery
                'Electrical machinery',
                'Electrical machinery and equip, sound and TV recorders & reproducers, parts',
                'Electrical machinery and equipment and parts and accessories thereof',
                'Electrical equipment, appliance, and component manufacturing',
                # Industrial machinery
                'Industrial machinery',
                # Computers and electronics
                'Computers',
                'Computer and electronic product manufacturing',
                # Telecommunications equipment
                'Telecommunications equipment',
                # Semiconductors and electronic components
                'Semiconductors',
                'Electronic components',
                # Chemicals
                'Chemicals',
                'Products of the chemical or allied industries',
                'Inorganic chemicals (Dec. 2024=100)',
                'Inorganic chemicals (Jan. 2025=100)',
                'Organic chemicals',
                'Organic chemicals (Jan. 2025=100)',
                'Chemical manufacturing',
                # Pharmaceuticals
                'Pharmaceuticals',
                'Pharmaceutical products',
                # Plastics and rubber
                'Plastics',
                'Plastics and articles thereof; rubber and articles thereof',
                'Plastics and articles thereof',
                'Plastics and rubber products manufacturing',
                'Rubber products',
                'Rubber and articles thereof',
                # Textiles
                'Textiles',
                'Textile and textile articles',
                'Textile and textile articles (Jan. 2025=100)',
                'Cotton, yarns and woven fabrics thereof',
                'Manmade filaments, yarns and woven fabrics (Jan. 2025=100)',
                'Manmade staple fibers, yarns & woven fabrics (Jan. 2025=100)',
                'Manmade staple fibers, yarns and woven fabrics (Jan. 2025=100)',
                'Wadding, felt and nonwovens; special yarns; twine, cordage, and ropes (Jan. 2025=100)',
                'Textile mills (Dec. 2023=100)',
                'Textile product mills (Dec. 2023=100)',
                # Apparel
                'Apparel',
                'Apparel manufacturing',
                'Articles of apparel and clothing accessories, knitted or crocheted (Dec. 2023=100)',
                'Articles of apparel and clothing accessories, not knitted or crocheted',
                'Made-up or worn textile articles (Dec. 2023=100)',
                # Footwear
                'Footwear',
                'Footwear and parts of such articles',
                # Paper products
                'Paper products',
                'Woodpulp, recovered paper, and paper products (Jan. 2025=100)',
                'Pulp wood, waste paper, and paperboard (Jan. 2025=100)',
                'Woodpulp and recovered paper (Dec. 2019=100)',
                'Paper and paperboard; articles of paper pulp, paper or paperboard (Jan. 2025=100)',
                'Paper manufacturing',
                'Paper manufacturing (Jan. 2025=100)',
                # Printed materials
                'Printed materials',
                # Metal products
                'Metal products',
                'Base metals and articles of base metals',
                'Iron and steel (Jan. 2025=100)',
                'Articles of iron or steel',
                'Copper and articles thereof',
                'Nickel and articles thereof (Jan. 2025=100)',
                'Aluminum and articles thereof',
                'Lead and articles thereof (Jan. 2025=100)',
                'Zinc and articles thereof (Jan. 2025=100)',
                'Tin and articles thereof (Jan. 2025=100)',
                'Base metals nesoi; cermets; articles thereof (Jan. 2025=100)',
                'Tools, implements, cutlery, spoons and forks, of base metal; parts thereof',
                'Miscellaneous articles of base metal',
                'Miscellaneous articles of base metal (Dec. 2022=100)',
                'Primary metal manufacturing',
                'Fabricated metal product manufacturing',
                # Fabricated metal products
                'Fabricated metal products',
                # Iron and steel
                'Iron and steel',
                # Nonferrous metals
                'Nonferrous metals',
                # Miscellaneous manufacturing
                'Miscellaneous manufacturing',
                'Miscellaneous manufactured articles',
                # Fertilizers
                'Fertilizers (Dec. 2022=100)',
                'Fertilizers (Jan. 2025=100)',
                # Soap and cleaning products
                'Soap, lubricants; waxes, candles, polishing products, and modeling paste (Dec. 2024=100)',
                'Tanning or dyeing extracts, dyes, paints varnish, putty, & inks (Dec. 2024=100)',
                # Albuminoidal substances
                'Albuminoidal substances; modified starches; glues; enzymes (Jan. 2025=100)',
                # Miscellaneous chemical products
                'Miscellaneous chemical products',
                # Essential oils and perfumery
                'Essential oils and resinoids; perfumery cosmetic or toilet preparations',
                # Raw hides and leather
                'Raw hides and skins other than furskins and leather (Jan. 2025=100)',
            ],
            'laus': ['Manufacturing'],
        },
        'relationship': BLS_ENRICHMENT.manufacturingSectorCorrelation
    },

    'retail_sector': {
        'description': 'Retail trade and sales',
        'sector_uri': BLS_ENRICHMENT.RetailSector,
        'keywords': {
            'cpi': [],
            'ppi': [
                # Trade services
                'Trade',
                'Final demand trade services',
                'Trade of finished goods',
                'Trade of personal consumption goods',
                'Trade of private capital equipment',
                'Trade of government purchased goods',
                'Trade of government purchased goods, excluding capital equipment',
                'Trade of government purchased capital equipment',
                'Trade of exports',
                'Trade services for intermediate demand',
                'Trade services for manufacturing industries',
                'Trade services for nonmanufacturing industries',
                # Wholesaling
                'Professional and commercial equipment wholesaling',
                'Apparel wholesaling',
                # Retailing
                'Health, beauty, and optical goods retailing',
                'Apparel, jewelry, footwear, and accessories retailing',
                'Computer hardware, software, and supplies retailing',
                'TV, video, and photographic equipment and supplies retailing',
                'Sporting goods, including boats, retailing',
                'Book retailing',
            ],
            'eci': ['Retail trade', 'Wholesale trade', 'Trade, transportation'],
            'jolts': ['Wholesale trade', 'Retail trade'],
            'empsit': [
                'Retail trade',
                'Motor vehicle and parts dealers',
                'Automobile dealers',
                'Other motor vehicle dealers',
                'Automotive parts, accessories, and tire retailers',
                'Building material and garden equipment and supplies dealers',
                'Food and beverage retailers',
                'Furniture, home furnishings, electronics, and appliance retailers',
                'Furniture and home furnishings retailers',
                'Electronics and appliance retailers',
                'General merchandise retailers',
                'Department stores',
                'Warehouse clubs, supercenters, and other general merchandise retailers',
                'Health and personal care retailers',
                'Gasoline stations and fuel dealers',
                'Sporting goods, hobby, musical instrument, book, and miscellaneous retailers',
                'Wholesale trade',
                'Merchant wholesalers, durable goods',
                'Merchant wholesalers, nondurable goods',
                'Wholesale trade agents and brokers',
                'Sales and office occupations',
                'Sales and related occupations',
                'Wholesale and retail trade',
            ],
            'ximpim': [
                'Consumer goods',
                'Household goods',
                'Furniture',
                'Home furnishings',
                'Appliances',
                'Clothing',
                'Footwear',
                'Jewelry',
                'Watches',
                'Toys and games',
                'Toys, games and sports equipment; parts and accessories thereof',
                'Sporting goods',
                'Books',
                'Headgear, umbrellas, artificial flowers, etc.',
            ],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.retailSectorCorrelation
    },

    'healthcare_sector': {
        'description': 'Healthcare and social assistance',
        'sector_uri': BLS_ENRICHMENT.HealthcareSector,
        'keywords': {
            'cpi': [
                'Medical care',
                'Medical care commodities',
                'Medicinal drugs',
                'Prescription drugs',
                'Nonprescription drugs',
                'Medical equipment and supplies',
                'Medical care services',
                'Professional services',
                'Physicians\' services',
                'Dental services',
                'Eyeglasses and eye care',
                'Services by other medical professionals',
                'Hospital and related services',
                'Hospital services',
                'Inpatient hospital services',
                'Outpatient hospital services',
                'Nursing homes and adult day services',
                'Care of invalids and elderly at home',
                'Health insurance',
            ],
            'ppi': [
                # Healthcare services
                'Physician care',
                'Medical laboratory and diagnostic imaging care',
                'Home health and hospice care',
                'Hospital outpatient care',
                'Dental care',
                'Hospital inpatient care',
                'Nursing home care',
                # Medical products
                'Medical, surgical & personal aid devices',
                'Medical, surgical, and personal aid devices',
                # Insurance
                'Health and medical insurance',
            ],
            'eci': ['Health care', 'Healthcare', 'Hospitals', 'Nursing', 'Social assistance'],
            'jolts': [
                'Private education and health services',
                'Private educational services',
                'Health care and social assistance',
            ],
            'empsit': [
                'Health care and social assistance',
                'Health care',
                'Ambulatory health care services',
                'Offices of physicians',
                'Offices of dentists',
                'Offices of other health practitioners',
                'Outpatient care centers',
                'Medical and diagnostic laboratories',
                'Home health care services',
                'Other ambulatory health care services',
                'Hospitals',
                'Nursing and residential care facilities',
                'Skilled nursing care facilities',
                'Residential intellectual and developmental disability, mental health, and substance abuse facilities',
                'Continuing care retirement communities and assisted living facilities for the elderly',
                'Other residential care facilities',
                'Social assistance',
                'Individual and family services',
                'Community food and housing, and emergency and other relief services',
                'Vocational rehabilitation services',
                'Child care services',
                'Private education and health services',
                'Education and health services',
            ],
            'ximpim': [
                'Pharmaceuticals',
                'Medicinal products',
                'Medical equipment',
                'Medical instruments',
                'Surgical instruments',
                'Diagnostic equipment',
                'Optical, photo, measuring, medical & musical instruments; & timepieces',
                'Optical, photographic, measuring and medical instruments',
                'Optical, photographic, measuring and medical instruments (Dec. 2023=100)',
            ],
            'laus': ['Education and health services'],
        },
        'relationship': BLS_ENRICHMENT.healthcareSectorCorrelation
    },

    'recreation_sector': {
        'description': 'Recreation and entertainment',
        'sector_uri': BLS_ENRICHMENT.RecreationSector,
        'keywords': {
            'cpi': [
                'Recreation',
                'Recreation commodities',
                'Video and audio products',
                'Video and audio',
                'Televisions',
                'Other video equipment',
                'Audio equipment',
                'Recorded music and music subscriptions',
                'Pets and pet products',
                'Pets, pet products and services',
                'Pet food and treats',
                'Purchase of pets, pet supplies, accessories',
                'Sporting goods',
                'Sports vehicles including bicycles',
                'Sports equipment',
                'Photographic equipment and supplies',
                'Photographic equipment',
                'Photography',
                'Recreational reading materials',
                'Newspapers and magazines',
                'Recreational books',
                'Other recreational goods',
                'Toys',
                'Toys, games, hobbies and playground equipment',
                'Sewing machines, fabric and supplies',
                'Music instruments and accessories',
                'Recreation services',
                'Video and audio services',
                'Cable, satellite, and live streaming television service',
                'Purchase, subscription, and rental of video',
                'Video discs and other media',
                'Subscription and rental of video and video games',
                'Pet services including veterinary',
                'Pet services',
                'Veterinarian services',
                'Photographers and photo processing',
                'Other recreation services',
                'Club membership for shopping clubs, fraternal, or other organizations, or participant sports fees',
                'Admissions',
                'Admission to movies, theaters, and concerts',
                'Admission to sporting events',
                'Fees for lessons or instructions',
            ],
            'ppi': [
                # Recreation products
                'Toys, games, and children\'s vehicles',
                'Sporting and athletic goods',
                # Recreation services
                'Membership dues and admissions and recreation facility use fees (partial)',
                'Recreational activity instruction fees (partial)',
                'Gaming receipts (partial)',
            ],
            'eci': [],
            'jolts': ['Arts, entertainment, and recreation'],
            'empsit': [
                'Arts, entertainment, and recreation',
                'Performing arts, spectator sports, and related industries',
                'Museums, historical sites, and similar institutions',
                'Amusement, gambling, and recreation industries',
            ],
            'ximpim': [
                'Toys and games',
                'Toys, games and sports equipment; parts and accessories thereof',
                'Sporting goods',
                'Books',
            ],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.recreationSectorCorrelation
    },

    'education_communication_sector': {
        'description': 'Education and communication services',
        'sector_uri': BLS_ENRICHMENT.EducationCommunicationSector,
        'keywords': {
            'cpi': [
                'Education and communication',
                'Education',
                'Communication',
                'Education and communication commodities',
                'Educational books and supplies',
                'College textbooks',
                'Education and communication services',
                'Tuition, other school fees, and childcare',
                'College tuition and fees',
                'Elementary and high school tuition and fees',
                'Day care and preschool',
                'Technical and business school tuition and fees',
                'Information technology commodities',
                'Information and information processing',
                'Information technology, hardware and services',
                'Computers, peripherals, and smart home assistants',
                'Computer software and accessories',
                'Telephone hardware, calculators, and other consumer information items',
                'Smartphones',
                'Postage and delivery services',
                'Postage',
                'Delivery services',
                'Telephone services',
                'Wireless telephone services',
                'Residential telephone services',
                'Internet services and electronic information providers',
            ],
            'ppi': [
                # Publishing and media
                'Sales of books',
                'Sales and subscriptions of periodicals and newspapers',
                'Application software publishing',
                'Advertising space sales in periodicals, newspapers, directories, and mailing lists',
                'Advertising space sales in periodicals and newspapers',
                'Advertising space sales in directories and mail lists',
                'Television advertising time sales',
                'Radio advertising time sales',
                'Internet advertising sales',
                'Network compensation from broadcast TV, cable TV, radio',
                # Telecommunications
                'Residential wired telecommunication services',
                'Business wired telecommunication services',
                'Wireless telecommunication services',
                'Cable and satellite subscriber services',
                'Internet access services',
                'Bundled wired telecommunications access services',
                'Bundled wired telecommunication access services',
                'Wired telephone services',
                # Data and IT
                'Data processing and related services',
            ],
            'eci': ['Educational services', 'Education and health services', 'Elementary and secondary schools',
                    'Junior colleges', 'Colleges', 'Universities', 'Schools', 'Information'],
            'jolts': ['Information'],
            'empsit': [
                'Private educational services',
                'Private education and health services',
                'State government education',
                'Local government education',
                'Education and health services',
                'Information',
                'Motion picture and sound recording industries',
                'Publishing industries',
                'Broadcasting and content providers',
                'Telecommunications',
                'Computing infrastructure providers, data processing, web hosting, and related services',
                'Web search portals, libraries, archives, and other information services',
            ],
            'ximpim': [
                'Books',
                'Printed materials',
                'Educational materials',
                'Telecommunications equipment',
                'Communications equipment',
                'Broadcasting equipment',
                'Computers',
                'Computer equipment',
                'Semiconductors',
                'Electronic components',
                'Office machines',
                'Data processing equipment',
                'Machinery, electrical equipment, TV image and sound recorders, parts, etc.',
            ],
            'laus': ['Information'],
        },
        'relationship': BLS_ENRICHMENT.educationCommunicationSectorCorrelation
    },

    'personal_care_sector': {
        'description': 'Personal care products and services',
        'sector_uri': BLS_ENRICHMENT.PersonalCareSector,
        'keywords': {
            'cpi': [
                'Personal care',
                'Personal care products',
                'Hair, dental, shaving, and miscellaneous personal care products',
                'Cosmetics, perfume, bath, nail preparations and implements',
                'Personal care services',
                'Haircuts and other personal care services',
                'Other personal services',
                'Miscellaneous personal services',
            ],
            'ppi': [
                'Cosmetics and other toiletries',
            ],
            'eci': [],
            'jolts': ['Other services'],
            'empsit': [
                'Other services',
                'Repair and maintenance',
                'Personal and laundry services',
                'Religious, grantmaking, civic, professional, and similar organizations',
            ],
            'ximpim': [],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.personalCareSectorCorrelation
    },

    'tobacco_sector': {
        'description': 'Tobacco and smoking products',
        'sector_uri': BLS_ENRICHMENT.TobaccoSector,
        'keywords': {
            'cpi': [
                'Tobacco and smoking products',
                'Cigarettes',
                'Tobacco products other than cigarettes',
            ],
            'ppi': ['Cigarettes'],
            'eci': [],
            'jolts': [],
            'empsit': ['Beverage, tobacco, and leather'],
            'ximpim': [],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.tobaccoSectorCorrelation
    },

    'miscellaneous_goods_sector': {
        'description': 'Miscellaneous goods and services',
        'sector_uri': BLS_ENRICHMENT.MiscellaneousGoodsSector,
        'keywords': {
            'cpi': [
                'Other goods and services',
                'Other goods',
                'Miscellaneous personal goods',
                'Stationery, stationery supplies, gift wrap',
                'Other services',
                'Legal services',
                'Funeral expenses',
                'Financial services',
                'Checking account and other bank services',
                'Tax return preparation and other accounting fees',
            ],
            'ppi': [
                # Other services
                'Other',
                'Legal services',
                'Tax preparation and planning',
                'Accounting services (partial)',
                'Architectural and engineering services',
                'Management, scientific, and technical consulting services',
                'Management consulting services',
                'Advertising and related services (partial)',
                'Advertising agency services',
                # Financial services
                'Consumer loans (partial)',
                'Business loans (partial)',
                'Deposit services (partial)',
                'Other credit intermediation, incl. trust services (partial)',
                'Securities brokerage, dealing, investment advice, and related services',
                'Portfolio management',
                'Investment banking',
                'Life insurance',
                'Disability insurance, including accidental death',
                'Property and casualty insurance',
                'Insurance',
                'Annuities',
                'Commissions from sales of insurance',
                # Employment services
                'Permanent placement services',
                'Executive search services',
                'Staffing services',
                # Other business services
                'Security guard services',
                'Janitorial services',
                'Waste collection',
                'Commercial and industrial machinery and equipment repair and maintenance',
                # Accommodation
                'Traveler accommodation services',
                # Jewelry
                'Jewelry, platinum and karat gold',
                'Costume jewelry and novelties',
                # Mobile homes
                'Mobile homes',
                # Mining services
                'Mining services',
                # Hides and skins
                'Hides and skins',
                # Logs and wood
                'Logs, bolts, timber, pulpwood, and woodchips',
                'Logs, bolts, timber, pulpwood, and wood chips',
            ],
            'eci': [],
            'jolts': [],
            'empsit': [],
            'ximpim': [
                'Pearls, stones, precious metals, imitation jewelry, and coins',
                'Pearls, precious stones, precious metals jewelry, coin (Dec. 2023=100)',
                'Pearls, precious stones, precious metals; jewelry, coin (Dec. 2023=100)',
            ],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.miscellaneousGoodsSectorCorrelation
    },

    'professional_services_sector': {
        'description': 'Professional and business services',
        'sector_uri': BLS_ENRICHMENT.ProfessionalServicesSector,
        'keywords': {
            'cpi': [],
            'ppi': [
                # Services less trade, transportation, and warehousing
                'Services less trade, transportation, and warehousing for intermediate demand',
                'Services less trade, transportation, and warehousing for manufacturing industries',
                'Services less trade, transportation, and warehousing for nonmanufacturing industries',
                'Final demand services less trade, transportation, and warehousing',
                'Finished services less trade, transportation, and warehousing',
                'Finished consumer services less trade, transportation, and warehousing',
                'Private capital investment services less trade, transportation, and warehousing',
                'Government purchased services less trade, transportation, and warehousing',
                'Gov. purchased services less trade, transportation, and warehousing, excl. capital investment',
                'Government purchased capital investment services less trade, transportation, and warehousing',
                'Services for export less trade, transportation, and warehousing',
                # Rental and leasing
                'Construction, mining, and forestry machinery and equipment rental and leasing',
            ],
            'eci': ['Professional and business services', 'Professional, scientific, and technical',
                    'Administrative and support'],
            'jolts': [ 'Professional and business services'],
            'empsit': [
                'Professional and business services',
                'Professional, scientific, and technical services',
                'Legal services',
                'Accounting, tax preparation, bookkeeping, and payroll services',
                'Architectural, engineering, and related services',
                'Specialized design services',
                'Computer systems design and related services',
                'Management, scientific, and technical consulting services',
                'Scientific research and development services',
                'Advertising, public relations, and related services',
                'Other professional, scientific, and technical services',
                'Management of companies and enterprises',
                'Administrative and support and waste management and remediation services',
                'Administrative and support services',
                'Office administrative services',
                'Facilities support services',
                'Employment services',
                'Temporary help services',
                'Business support services',
                'Travel arrangement and reservation services',
                'Investigation and security services',
                'Services to buildings and dwellings',
                'Other support services',
                'Waste management and remediation services',
                'Management, professional, and related occupations',
                'Management, business, and financial operations occupations',
                'Professional and related occupations',
                'Office and administrative support occupations',
            ],
            'ximpim': [],
            'laus': ['Professional and business services'],
        },
        'relationship': BLS_ENRICHMENT.professionalServicesSectorCorrelation
    },

    'leisure_hospitality_sector': {
        'description': 'Leisure, hospitality, and entertainment',
        'sector_uri': BLS_ENRICHMENT.LeisureHospitalitySector,
        'keywords': {
            'cpi': [],
            'ppi': [],
            'eci': ['Leisure and hospitality', 'Accommodation and food'],
            'jolts': [
                'Leisure and hospitality',
                'Arts, entertainment, and recreation',
                'Accommodation and food services',
            ],
            'empsit': [
                'Leisure and hospitality',
                'Accommodation and food services',
                'Accommodation',
            ],
            'ximpim': [],
            'laus': ['Leisure and hospitality'],
        },
        'relationship': BLS_ENRICHMENT.leisureHospitalitySectorCorrelation
    },

    'government_sector': {
        'description': 'Government employment',
        'sector_uri': BLS_ENRICHMENT.GovernmentSector,
        'keywords': {
            'cpi': [],
            'ppi': [
                # Government purchases
                'Government purchased goods',
                'Government purchased services',
                'Government purchased goods, excluding foods and energy',
                'Government purchased goods excluding foods, energy, and capital equipment',
                'Government purchased capital equipment',
                'Government purchased energy',
                'Government purchased foods',
                'Trade of government purchased goods',
                'Trade of government purchased goods, excluding capital equipment',
                'Trade of government purchased capital equipment',
                'Transportation of government passengers',
                'Transportation and warehousing of government purchased goods',
                'Government purchased capital investment services less trade, transportation, and warehousing',
                'Total government purchased capital investment (goods, services, construction)',
                'Government purchases, defense',
                'Government purchases, non-defense',
                'Total government purchases',
                'Private and government purchased capital equipment',
                'Private and government purchased capital investment services',
                'Total private and government purchased capital investment',
            ],
            'eci': ['State and local government', 'Public administration'],
            'jolts': [
                'Government',
                'Federal',
                'State and local',
                'State and local education',
                'State and local, excluding education',
            ],
            'empsit': [
                'Government',
                'Federal',
                'Federal, except U.S. Postal Service',
                'U.S. Postal Service',
                'State government',
                'State government education',
                'State government, excluding education',
                'Local government',
                'Local government education',
                'Local government, excluding education',
                'Government workers',
            ],
            'ximpim': [],
            'laus': ['Government'],
        },
        'relationship': BLS_ENRICHMENT.governmentSectorCorrelation
    },

    'information_sector': {
        'description': 'Information and communications',
        'sector_uri': BLS_ENRICHMENT.InformationSector,
        'keywords': {
            'cpi': [
                'Information and information processing',
                'Information technology, hardware and services',
                'Communication',
            ],
            'ppi': [],
            'eci': ['Information'],
            'jolts': ['Information'],
            'empsit': [
                'Information',
                'Motion picture and sound recording industries',
                'Publishing industries',
                'Broadcasting and content providers',
                'Telecommunications',
                'Computing infrastructure providers, data processing, web hosting, and related services',
                'Web search portals, libraries, archives, and other information services',
            ],
            'ximpim': [
                'Telecommunications equipment',
                'Communications equipment',
                'Broadcasting equipment',
                'Printed materials',
                'Books',
                'Newspapers',
                'Periodicals',
            ],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.informationSectorCorrelation
    },

    'financial_sector': {
        'description': 'Financial activities and services',
        'sector_uri': BLS_ENRICHMENT.FinancialSector,
        'keywords': {
            'cpi': [
                'Financial services',
                'Checking account and other bank services',
                'Tax return preparation and other accounting fees',
            ],
            'ppi': [],
            'eci': ['Financial activities', 'Finance and insurance', 'Credit intermediation',
                    'Insurance carriers', 'Real estate'],
            'jolts': [
                'Financial activities',
                'Finance and insurance',
                'Real estate and rental and leasing',
            ],
            'empsit': [
                'Financial activities',
                'Finance and insurance',
                'Monetary authorities-central bank',
                'Credit intermediation and related  activities',
                'Depository credit intermediation',
                'Commercial banking',
                'Nondepository credit intermediation',
                'Activities related to credit intermediation',
                'Securities, commodity contracts, funds, trusts, and other financial vehicles, investments, and related activities',
                'Insurance carriers and related activities',
                'Real estate and rental and leasing',
                'Real estate',
                'Rental and leasing services',
            ],
            'ximpim': [],
            'laus': ['Financial activities'],
        },
        'relationship': BLS_ENRICHMENT.financialSectorCorrelation
    },

    'natural_resources_sector': {
        'description': 'Natural resources, farming, fishing, forestry',
        'sector_uri': BLS_ENRICHMENT.NaturalResourcesSector,
        'keywords': {
            'cpi': [],
            'ppi': [
                # Unprocessed materials
                'Unprocessed nonfood materials',
                'Unprocessed nonfood materials except fuel',
                'Unprocessed nonfood materials except fuel to manufacturing industries',
                'Unprocessed nonfood materials except fuel to nonmanufacturing industries',
                'Unprocessed nonfood materials less energy',
                'Unprocessed materials less agricultural products',
                'Unprocessed materials less energy',
            ],
            'eci': ['Natural resources, construction, and maintenance',
                    'Construction, extraction, farming, fishing, and forestry'],
            'jolts': [],
            'empsit': [
                'Logging',
                'Natural resources, construction, and maintenance occupations',
                'Farming, fishing, and forestry occupations',
                'Agriculture and related industries',
                'Agriculture and related private wage and salary workers',
            ],
            'ximpim': [
                'Agricultural products',
                'Forestry products',
                'Fish and seafood',
                'Timber',
                'Logs',
                'Wood',
                'Cork',
                'Animal products',
                'Hides and skins',
                'Crude fertilizers',
                'Ores',
                'Metal ores',
                'Minerals',
            ],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.naturalResourcesSectorCorrelation
    },

    'construction_trades_sector': {
        'description': 'Construction and extraction trades',
        'sector_uri': BLS_ENRICHMENT.ConstructionTradesSector,
        'keywords': {
            'cpi': [],
            'ppi': [],
            'eci': ['Construction', 'Installation, maintenance, and repair'],
            'jolts': [],
            'empsit': [
                'Construction and extraction occupations',
                'Natural resources, construction, and maintenance occupations',
            ],
            'ximpim': [
                'Construction materials',
                'Building materials',
            ],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.constructionTradesSectorCorrelation
    },

    'apparel_sector': {
        'description': 'Apparel and clothing',
        'sector_uri': BLS_ENRICHMENT.ApparelSector,
        'keywords': {
            'cpi': [
                'Apparel',
                'Apparel less footwear',
                'Men\'s and boys\' apparel',
                'Men\'s apparel',
                'Men\'s suits, sport coats, and outerwear',
                'Men\'s underwear, nightwear, swimwear, and accessories',
                'Men\'s shirts and sweaters',
                'Men\'s pants and shorts',
                'Boys\' apparel',
                'Women\'s and girls\' apparel',
                'Women\'s apparel',
                'Women\'s outerwear',
                'Women\'s dresses',
                'Women\'s suits and separates',
                'Women\'s underwear, nightwear, swimwear, and accessories',
                'Girls\' apparel',
                'Footwear',
                'Men\'s footwear',
                'Boys\' and girls\' footwear',
                'Women\'s footwear',
                'Infants\' and toddlers\' apparel',
                'Jewelry and watches',
                'Watches',
                'Jewelry',
            ],
            'ppi': [
                'Women\'s, girls\', and infants\' apparel',
                'Men\'s and boys\' apparel',
                'Footwear',
            ],
            'eci': [],
            'jolts': [],
            'empsit': [],
            'ximpim': [],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.apparelSectorCorrelation
    },

    'capital_investment_sector': {
        'description': 'Capital investment goods and services',
        'sector_uri': BLS_ENRICHMENT.CapitalInvestmentSector,
        'keywords': {
            'cpi': [],
            'ppi': [
                # Capital equipment and investment
                'Private capital investment services',
                'Private capital investment services less trade, transportation, and warehousing',
                'Total private capital investment (goods, services, and construction)',
                'Finished distributive services',
                'Intermediate distributive services',
                'Final demand distributive services',
                'Supplies for intermediate demand',
                'Supplies to manufacturing industries',
                'Supplies to nonmanufacturing industries',
                'Supplies to nonmanufacturing industries, feeds',
                'Supplies to nonmanufacturing industries, other than feeds',
                'Containers for intermediate demand',
                # Stage-based categories
                'Stage 4 intermediate demand',
                'Stage 3 intermediate demand',
                'Stage 2 intermediate demand',
                'Stage 1 intermediate demand',
                'Inputs to stage 4 goods producers',
                'Inputs to stage 4 services producers',
                'Inputs to stage 3 goods producers',
                'Inputs to stage 3 services producers',
                'Inputs to stage 2 goods producers',
                'Inputs to stage 2 services producers',
                'Inputs to stage 1 goods producers',
                'Inputs to stage 1 services producers',
            ],
            'eci': [],
            'jolts': [],
            'empsit': [],
            'ximpim': [],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.capitalInvestmentSectorCorrelation
    },

    'exports_sector': {
        'description': 'Exports and international trade',
        'sector_uri': BLS_ENRICHMENT.ExportsSector,
        'keywords': {
            'cpi': [],
            'ppi': [
                # Exports
                'Total exports',
                'Goods for export',
                'Services for export',
                'Goods for export, excluding foods and energy',
                'Trade of exports',
                'Transportation of passengers for export',
                'Transportation and warehousing of exports',
                'Services for export less trade, transportation, and warehousing',
                'Final demand less exports',
            ],
            'eci': [],
            'jolts': [],
            'empsit': [],
            'ximpim': [
                # Imports and exports
                'IMPORTS',
                'EXPORTS',
                'Allimports',
                'Allexports',
                'All imports excluding food and fuels (Dec. 2010=100)',
                'All exports excluding food and fuels (Dec. 2010=100)',
                'Nonfuelimports',
                'Agri-culturalexports',
                'Non-agriculturalexports',
                'Nonagricultural commodities',
            ],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.exportsSectorCorrelation
    },

    'personal_consumption_sector': {
        'description': 'Personal consumption goods and services',
        'sector_uri': BLS_ENRICHMENT.PersonalConsumptionSector,
        'keywords': {
            'cpi': [],
            'ppi': [
                # Personal consumption
                'Personal consumption',
                'Personal consumption goods (finished consumer goods)',
                'Personal consumption goods less energy',
                'Personal consumption goods less foods',
                'Personal consumption nondurable goods less foods',
                'Personal consumption services',
                'Personal consumption less trade services',
                'Personal consumption less distributive services',
                'Personal consumption less foods and energy',
                'Personal consumption less foods, energy, and trade services',
                'Personal consumption less foods, energy, and distributive services',
                'Personal consumption goods plus personal consumption distributive services',
            ],
            'eci': [],
            'jolts': [],
            'empsit': [],
            'ximpim': [],
            'laus': [],
        },
        'relationship': BLS_ENRICHMENT.personalConsumptionSectorCorrelation
    },

    'geographic_regions_sector': {
        'description': 'Geographic regions and trading partners',
        'sector_uri': BLS_ENRICHMENT.GeographicRegionsSector,
        'keywords': {
            'cpi': [],
            'ppi': [],
            'eci': [],
            'jolts': ['Northeast', 'South', 'Midwest', 'West'],
            'empsit': [],
            'ximpim': [
                # Industrialized countries
                'Industrialized Countries',
                # North America
                'Canada',
                # Europe
                'European Union',
                'Europe',
                'France (Dec. 2003=100)',
                'Germany (Dec. 2003=100)',
                'Germany',
                'United Kingdom (Dec. 2003=100)',
                # Latin America
                'Latin America',
                'Latin America/Caribbean',
                'Mexico (Dec. 2003=100)',
                'Mexico',
                # Asia Pacific
                'Pacific Rim (Dec. 2003=100)',
                'Pacific Rim',
                'Asia',
                'China (Dec. 2003=100)',
                'China',
                'Japan',
                'Taiwan (Dec. 2018=100)',
                'Asian NICs',
                'ASEAN (Dec. 2003=100)',
                'Asia Near East (Dec. 2003=100)',
            ],
        },
        'relationship': BLS_ENRICHMENT.geographicRegionsSectorCorrelation
    },

    'employment_size_sector': {
        'description': 'Employment by establishment size',
        'sector_uri': BLS_ENRICHMENT.EmploymentSizeSector,
        'keywords': {
            'cpi': [],
            'ppi': [],
            'eci': [],
            'jolts': [
                # Total categories
                'Total',
                'Total private',
                # Establishment size classes
                '1 to 9 employees',
                '10 to 49 employees',
                '50 to 249 employees',
                '250 to 999 employees',
                '1,000 to 4,999 employees',
                '5,000 or more employees',
            ],
            'empsit': [],
            'ximpim': [],
            'laus': [
                # US States
                'State',
                'Alabama',
                'Alaska',
                'Arizona',
                'Arkansas',
                'California',
                'Colorado',
                'Connecticut',
                'Delaware',
                'District of Columbia',
                'Florida',
                'Georgia',
                'Hawaii',
                'Idaho',
                'Illinois',
                'Indiana',
                'Iowa',
                'Kansas',
                'Kentucky',
                'Louisiana',
                'Maine',
                'Maryland',
                'Massachusetts',
                'Michigan',
                'Minnesota',
                'Mississippi',
                'Missouri',
                'Montana',
                'Nebraska',
                'Nevada',
                'New Hampshire',
                'New Jersey',
                'New Mexico',
                'New York',
                'North Carolina',
                'North Dakota',
                'Ohio',
                'Oklahoma',
                'Oregon',
                'Pennsylvania',
                'Rhode Island',
                'South Carolina',
                'South Dakota',
                'Tennessee',
                'Texas',
                'Utah',
                'Vermont',
                'Virginia',
                'Washington',
                'West Virginia',
                'Wisconsin',
                'Wyoming',
                # US Territories
                'Puerto Rico',
                'Virgin Islands',
            ],
        },
        'relationship': BLS_ENRICHMENT.employmentSizeSectorCorrelation
    },
}