from constructs import Construct
import aws_cdk as cdk
from aws_cdk import (
    Stack,
    aws_glue as glue,
    aws_iam as iam,
    aws_s3 as s3,
    aws_ssm as ssm,
)


class GlueStack(Stack):
    """AWS Glue resources for the PyG Knowledge Graph Builder.

    Creates:
        - Glue Job for build_graph.py with sensible defaults
        - SSM Parameters for blue/green deployment version tracking
        - SSM Parameters for notebook discovery of job configuration

    Blue/Green Deployment Support:
        - Script and wheel paths are versioned in S3:
            s3://<artifacts>/glue-scripts/<version>/build_graph.py
            s3://<artifacts>/glue-wheels/<version>/*.whl
        - SSM parameters track active version for external CodeDeploy
        - Job name is stable — CodeDeploy updates script location in-place

    Notebook Override Support:
        SageMaker Studio notebooks invoke via start_job_run and can
        override any combination of parameters:

        Infrastructure overrides (top-level start_job_run kwargs):
            WorkerType       — e.g., 'G.2X', 'G.4X'
            NumberOfWorkers  — e.g., 5, 10, 20
            Timeout          — minutes

        Pipeline parameter overrides (via Arguments dict, merged with
        job defaults — only keys you specify are overridden):
            --mode, --source_bucket, --source_prefix, --output_bucket,
            --enriched_rdf_key, --pyg_output_key, --time_period,
            --rdf_format, --enable_ontology_mapping, --pyg_config

        max_concurrent_runs > 1 allows parallel experiments.

    S3 Path Conventions:
        Raw input:     s3://<data>/raw/bls/2024/12/
                       s3://<data>/raw/sec/2024/12/
        Enriched:      s3://<data>/enriched/year=2024/month=12/<run_id>/
        PyG output:    s3://<output>/pyg/year=2024/month=12/<run_id>/
        Manifests:     s3://<output>/manifests/year=2024/month=12/

        The --source_prefix default points to raw/ and the notebook
        appends the source/date path. The --enriched_rdf_key and
        --pyg_output_key are auto-generated by the notebook helper
        with matching date partitions.
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        project_name: str,
        environment: str,
        artifacts_bucket: s3.IBucket,
        data_bucket: s3.IBucket,
        output_bucket: s3.IBucket,
        glue_role: iam.IRole,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self._project_name = project_name
        self._environment = environment
        self._artifacts_bucket = artifacts_bucket
        self._data_bucket = data_bucket
        self._output_bucket = output_bucket
        self._glue_role = glue_role

        # Read Glue configuration from CDK context
        self._glue_version = (
            self.node.try_get_context("glue_version") or "4.0"
        )
        self._python_version = (
            self.node.try_get_context("python_version") or "3"
        )
        self._default_worker_type = (
            self.node.try_get_context("default_worker_type") or "G.2X"
        )
        self._default_number_of_workers = int(
            self.node.try_get_context("default_number_of_workers") or 10
        )
        self._timeout_minutes = int(
            self.node.try_get_context("timeout_minutes") or 120
        )
        self._max_retries = int(
            self.node.try_get_context("max_retries") or 0
        )
        self._max_concurrent_runs = int(
            self.node.try_get_context("max_concurrent_runs") or 3
        )
        self._enable_spark_ui = (
            self.node.try_get_context("enable_spark_ui") is not False
        )
        self._spark_ui_log_prefix = (
            self.node.try_get_context("spark_ui_log_prefix")
            or "spark-ui-logs/"
        )

        # stock market definitions
        self._market_sector_definitions_bucket = (
                self.node.try_get_context("market_sector_definitions_bucket") or ""
        )
        self._market_sector_definitions_key = (
                self.node.try_get_context("market_sector_definitions_key") or ""
        )

        # Stable job name (no version suffix for blue/green)
        self._job_name = (
            f"{self._project_name}-{self._environment}-build-graph"
        )

        # SSM parameters for blue/green version tracking
        self._version_param = self._create_version_parameter()

        # Main Glue job
        self._build_graph_job = self._create_build_graph_job()

        # SSM parameters for notebook discovery
        self._create_discovery_parameters()

        self._add_outputs()

    # ------------------------------------------------------------------
    # SSM parameters
    # ------------------------------------------------------------------
    def _create_version_parameter(self) -> ssm.StringParameter:
        """SSM parameter tracking the active deployment version.

        CodeDeploy (separate repo) reads and updates this during
        blue/green cutover. Maps to S3 prefix:
            s3://<artifacts>/glue-scripts/<version>/
            s3://<artifacts>/glue-wheels/<version>/
        """
        return ssm.StringParameter(
            self,
            "ActiveVersionParam",
            parameter_name=(
                f"/{self._project_name}/{self._environment}/active-version"
            ),
            string_value="initial",
            description=(
                f"Active deployment version for {self._project_name} "
                f"Glue jobs. Updated by CodeDeploy during blue/green "
                f"deployments."
            ),
            tier=ssm.ParameterTier.STANDARD,
        )

    def _create_discovery_parameters(self) -> None:
        """SSM parameters for notebook discovery of job configuration.

        Notebooks read these to construct start_job_run calls without
        hardcoding bucket names, job names, or S3 paths.
        """
        params = {
            "JobNameParam": (
                "glue-job-name/build-graph",
                self._job_name,
                "Glue job name for build-graph.",
            ),
            "DataBucketParam": (
                "buckets/data",
                self._data_bucket.bucket_name,
                "S3 bucket for raw and enriched data.",
            ),
            "OutputBucketParam": (
                "buckets/output",
                self._output_bucket.bucket_name,
                "S3 bucket for PyG outputs and manifests.",
            ),
            "ArtifactsBucketParam": (
                "buckets/artifacts",
                self._artifacts_bucket.bucket_name,
                "S3 bucket for Glue scripts and wheels.",
            ),
            "DefaultWorkerTypeParam": (
                "defaults/worker-type",
                self._default_worker_type,
                "Default Glue worker type.",
            ),
            "DefaultNumberOfWorkersParam": (
                "defaults/number-of-workers",
                str(self._default_number_of_workers),
                "Default number of Glue workers.",
            ),
        }

        for logical_id, (suffix, value, description) in params.items():
            ssm.StringParameter(
                self,
                logical_id,
                parameter_name=(
                    f"/{self._project_name}/{self._environment}/{suffix}"
                ),
                string_value=value,
                description=description,
            )

    # ------------------------------------------------------------------
    # S3 paths
    # ------------------------------------------------------------------
    def _get_script_location(self) -> str:
        return (
            f"s3://{self._artifacts_bucket.bucket_name}"
            f"/glue-scripts/initial/build_graph.py"
        )

    def _get_extra_py_files(self) -> str:
        return (
            f"s3://{self._artifacts_bucket.bucket_name}"
            f"/glue-scripts/initial/glue_jobs.zip"
        )

    def _get_additional_python_modules(self) -> str:
        """S3 paths to pre-built wheel files.

        Wheels are uploaded per version:
            s3://<bucket>/glue-wheels/<version>/*.whl
        """
        base = (
            f"s3://{self._artifacts_bucket.bucket_name}"
            f"/glue-wheels/initial"
        )
        return ",".join(
            [
                f"{base}/rdflib-7.1.3-py3-none-any.whl",
                f"{base}/torch-2.3.0+cpu-cp310-cp310-linux_x86_64.whl",
                f"{base}/torch_geometric-2.5.3-py3-none-any.whl",
            ]
        )

    # ------------------------------------------------------------------
    # Default arguments
    # ------------------------------------------------------------------
    def _build_default_arguments(self) -> dict:
        """Construct default arguments for the Glue job.

        These defaults are used when the job is started without overrides.
        Notebooks override any subset via start_job_run(Arguments={...}).
        Only keys present in the Arguments dict are overridden; all other
        defaults are preserved.

        Note: WorkerType and NumberOfWorkers are top-level job properties,
        not default arguments. Notebooks override them via:
            start_job_run(WorkerType='G.4X', NumberOfWorkers=20, ...)
        """
        default_args = {
            # ---- Pipeline parameters (from build_graph.py) ----
            "--mode": "full",
            "--source_bucket": self._data_bucket.bucket_name,
            "--source_prefix": "raw/",
            "--output_bucket": self._output_bucket.bucket_name,
            "--enriched_rdf_key": "",
            "--pyg_output_key": "",
            "--enable_ontology_mapping": "false",
            "--time_period": "",
            "--rdf_format": "turtle",
            "--pyg_config": "",

            # ---- Glue platform parameters ----
            "--extra-py-files": self._get_extra_py_files(),
            "--additional-python-modules": (
                self._get_additional_python_modules()
            ),

            # Continuous logging
            "--enable-continuous-cloudwatch-log": "true",
            "--continuous-log-logGroup": (
                f"/aws-glue/{self._project_name}/{self._environment}"
            ),
            "--enable-continuous-log-filter": "true",

            # Metrics
            "--enable-metrics": "true",

            # Job bookmarks disabled (stateless pipeline)
            "--job-bookmark-option": "job-bookmark-disable",

            # Spark configuration
            "--conf": (
                "spark.serializer="
                "org.apache.spark.serializer.KryoSerializer"
                " --conf spark.sql.adaptive.enabled=true"
                " --conf spark.sql.adaptive.coalescePartitions.enabled=true"
            ),

            # Deployment version tracking
            "--deployment_version": "initial",

            # Market sector definitions — S&P 500 tickers CSV
            # produced by the market-morning pipeline.
            # If empty or unavailable, falls back to hardcoded defaults.
            "--market_sector_definitions_bucket": self._market_sector_definitions_bucket,
            "--market_sector_definitions_key": self._market_sector_definitions_key,
        }

        # Spark UI
        if self._enable_spark_ui:
            default_args["--enable-spark-ui"] = "true"
            default_args["--spark-event-logs-path"] = (
                f"s3://{self._artifacts_bucket.bucket_name}"
                f"/{self._spark_ui_log_prefix}"
            )

        return default_args

    # ------------------------------------------------------------------
    # Glue job
    # ------------------------------------------------------------------
    def _create_build_graph_job(self) -> glue.CfnJob:
        """Create the main Glue job.

        The job defines default WorkerType and NumberOfWorkers, but
        notebooks can override both at run time:

            glue_client.start_job_run(
                JobName='pyg-...-build-graph',
                WorkerType='G.4X',
                NumberOfWorkers=20,
                Arguments={
                    '--mode': 'pyg_only',
                    '--time_period': '2024-12',
                    '--enriched_rdf_key': (
                        'enriched/year=2024/month=12/abc123/'
                        'knowledge_graph.ttl'
                    ),
                    '--pyg_output_key': (
                        'pyg/year=2024/month=12/def456/'
                        'hetero_data.pt'
                    ),
                    '--pyg_config': '{"node_types": ["cpi_Index"]}',
                },
            )

        max_concurrent_runs > 1 allows parallel experiments from
        notebooks (e.g., different PyG configs on same enriched data).
        """
        return glue.CfnJob(
            self,
            "BuildGraphJob",
            name=self._job_name,
            description=(
                "Builds enriched RDF knowledge graphs and constructs "
                "PyTorch Geometric HeteroData objects from multi-source "
                "economic, financial, market, and environmental data. "
                "Supports full, enrichment_only, and pyg_only modes. "
                "All parameters overridable at run time from notebooks."
            ),
            role=self._glue_role.role_arn,
            command=glue.CfnJob.JobCommandProperty(
                name="glueetl",
                python_version=self._python_version,
                script_location=self._get_script_location(),
            ),
            glue_version=self._glue_version,
            worker_type=self._default_worker_type,
            number_of_workers=self._default_number_of_workers,
            timeout=self._timeout_minutes,
            max_retries=self._max_retries,
            execution_property=glue.CfnJob.ExecutionPropertyProperty(
                max_concurrent_runs=self._max_concurrent_runs,
            ),
            default_arguments=self._build_default_arguments(),
            tags={
                "Project": self._project_name,
                "Environment": self._environment,
                "Component": "build-graph",
            },
        )

    # ------------------------------------------------------------------
    # Outputs
    # ------------------------------------------------------------------
    def _add_outputs(self) -> None:
        cdk.CfnOutput(
            self,
            "BuildGraphJobName",
            value=self._job_name,
            export_name=(
                f"{self._project_name}-{self._environment}"
                f"-build-graph-job-name"
            ),
        )

        cdk.CfnOutput(
            self,
            "ActiveVersionParamName",
            value=self._version_param.parameter_name,
            export_name=(
                f"{self._project_name}-{self._environment}"
                f"-active-version-param"
            ),
        )

        cdk.CfnOutput(
            self,
            "ScriptBasePath",
            value=(
                f"s3://{self._artifacts_bucket.bucket_name}/glue-scripts/"
            ),
            description=(
                "Base S3 path for Glue scripts. "
                "Append <version>/build_graph.py for specific version."
            ),
            export_name=(
                f"{self._project_name}-{self._environment}"
                f"-script-base-path"
            ),
        )

        cdk.CfnOutput(
            self,
            "WheelsBasePath",
            value=(
                f"s3://{self._artifacts_bucket.bucket_name}/glue-wheels/"
            ),
            description=(
                "Base S3 path for dependency wheels. "
                "Append <version>/*.whl for specific version."
            ),
            export_name=(
                f"{self._project_name}-{self._environment}"
                f"-wheels-base-path"
            ),
        )

        cdk.CfnOutput(
            self,
            "DefaultWorkerType",
            value=self._default_worker_type,
            export_name=(
                f"{self._project_name}-{self._environment}"
                f"-default-worker-type"
            ),
        )

        cdk.CfnOutput(
            self,
            "DefaultNumberOfWorkers",
            value=str(self._default_number_of_workers),
            export_name=(
                f"{self._project_name}-{self._environment}"
                f"-default-number-of-workers"
            ),
        )

    @property
    def build_graph_job(self) -> glue.CfnJob:
        return self._build_graph_job

    @property
    def build_graph_job_name(self) -> str:
        return self._job_name

    @property
    def version_parameter(self) -> ssm.StringParameter:
        return self._version_param